import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";

export const ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "..",
);
export const GENERATED_DIR = path.join(ROOT, "docs", "generated");

export function readJson<T>(relativePath: string): T {
  return JSON.parse(fs.readFileSync(path.join(ROOT, relativePath), "utf8"));
}

export function readYaml(relativePath: string): unknown {
  return parse(fs.readFileSync(path.join(ROOT, relativePath), "utf8"));
}

export function listFiles(dir: string, predicate: (file: string) => boolean): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...listFiles(full, predicate));
    if (entry.isFile() && predicate(full)) out.push(full);
  }
  return out.sort();
}

export function writeGenerated(name: string, contents: string): void {
  fs.mkdirSync(GENERATED_DIR, { recursive: true });
  fs.writeFileSync(path.join(GENERATED_DIR, name), `${contents.trimEnd()}\n`);
}

export function generatedHeader(title: string): string {
  return `# ${title}\n\nGenerated by \`pnpm --filter @workspace/scripts run docs:generate\`.\nCommit: ${process.env.GITHUB_SHA ?? process.env.REPLIT_GIT_COMMIT_SHA ?? "unknown"}.\nDo not edit by hand.\n`;
}
