import { Router, type IRouter } from "express";
import tripsRouter from "./trips";
import documentsRouter from "./documents";
import aiRouter from "./ai";
import wishlistRouter from "./wishlist";
import photosRouter from "./photos";
import remindersRouter from "./reminders";
import destinationsRouter from "./destinations";
import settingsRouter from "./settings";
import magnetsRouter from "./magnets";
import googleCalendarRouter from "./google-calendar";
import travelCalendarRouter from "./travel-calendar";
import connectedCalendarsRouter from "./connected-calendars";
import calendarTripSuggestionsRouter from "./calendar-trip-suggestions";
import gmailRouter from "./gmail";
import mapsRouter from "./maps";
import walletRouter from "./wallet";
import cardLayoutRouter from "./card-layout";
import documentTypesRouter from "./document-types";

const router: IRouter = Router();

router.use(tripsRouter);
router.use(cardLayoutRouter);
router.use(documentsRouter);
router.use(aiRouter);
router.use(wishlistRouter);
router.use(photosRouter);
router.use(remindersRouter);
router.use(destinationsRouter);
router.use(settingsRouter);
router.use(magnetsRouter);
router.use(googleCalendarRouter);
router.use(travelCalendarRouter);
router.use(connectedCalendarsRouter);
router.use(calendarTripSuggestionsRouter);
router.use(gmailRouter);
router.use(mapsRouter);
router.use(walletRouter);
router.use(documentTypesRouter);

export default router;
