/**
 * check-backup-coverage.ts
 *
 * Guards against schema tables silently missing from the backup/restore scripts.
 *
 * Extracts every table name defined via pgTable() in lib/db/src/schema/*.ts and
 * checks that each one either:
 *   (a) appears in a copyTable() call in both backup-to-replit.ts AND
 *       restore-from-replit.ts, or
 *   (b) is listed in INTENTIONAL_SKIPS below with an explicit, non-TODO reason.
 *
 * Exits 1 if any table is missing from either script and not in INTENTIONAL_SKIPS.
 * This catches the recurring class of bug where a new feature adds a table to the
 * Drizzle schema but forgets to update the hand-maintained backup/restore scripts.
 *
 * Run via: pnpm --filter @workspace/scripts run check-backup-coverage
 * Also called from pre-publish.sh and CI.
 */

import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

const REPO_ROOT = join(import.meta.dirname, "..", "..");

// ---------------------------------------------------------------------------
// Tables that are intentionally absent from the backup/restore scripts.
// Every entry MUST have a brief reason — "skip" alone is not enough.
// "TODO:" prefixes are NOT accepted here; if a table contains user data,
// add it to both scripts instead of exempting it.
// ---------------------------------------------------------------------------
export const INTENTIONAL_SKIPS: Record<string, string> = {
  // ── Ephemeral / regeneratable tokens ─────────────────────────────────────
  password_reset_tokens:
    "ephemeral — users re-request a reset link after a restore",
  phone_verification_codes:
    "ephemeral — users re-verify their number after a restore",

  // ── Operational / scheduling logs ─────────────────────────────────────────
  scheduler_runs:
    "operational log — not user data; timing history has no restore value",
  comm_checks:
    "health-check ping records — operational, regenerated on every startup",
  elaine_broadcast_log:
    "operational log — pruned regularly (see task #586); not user data",
  elaine_turn_traces:
    "debug/observability traces — operational, not user-owned data",
  slack_webhook_deliveries:
    "dedup IDs for Slack webhook deliveries — ephemeral; Slack dedup can safely restart after a restore",

  // ── Generated / re-derivable content ─────────────────────────────────────
  elaine_daily_briefs:
    "AI-generated daily briefs — re-generated on demand; not user-authored data",
  hallmark_catalog:
    "scraped Hallmark product catalog — re-crawled from the source website",
  hallmark_historical_catalog:
    "scraped historical price catalog — re-crawled from the source website",
  hallmark_hooh_catalog:
    "scraped HooH collector prices — re-crawled from the source website",
  travels_doc_chunks:
    "vector-search chunks derived from travels_trip_documents — regenerated by re-running AI extraction",

  // ── Session-like channel state ─────────────────────────────────────────────
  elaine_slack_conversations:
    "per-channel Slack conversation context — ephemeral session state; reconnects after restore",

  // ── Push-notification device tokens ───────────────────────────────────────
  messenger_push_subscriptions:
    "device push-notification subscriptions — users re-subscribe on next app open",
};

// ---------------------------------------------------------------------------
// Tables present in backup but NOT in restore, where the asymmetry is
// intentional and safe. Only auto-generated/monitoring data belongs here —
// never user-authored data or user preferences.
// ---------------------------------------------------------------------------
export const RESTORE_SKIP_EXTRA: Record<string, string> = {
  travel_monitoring_baselines:
    "auto-generated monitoring baselines — rebuilt automatically on the next monitoring check; safe to skip on restore",
  travel_monitoring_observations:
    "auto-scraped monitoring observations — rebuilt automatically on the next monitoring check; safe to skip on restore",
};

// ---------------------------------------------------------------------------
// Helpers (exported for unit tests)
// ---------------------------------------------------------------------------

export function extractSchemaTables(schemaDir: string): Set<string> {
  const files = readdirSync(schemaDir).filter(
    (f) => f.endsWith(".ts") && f !== "index.ts",
  );
  const tables = new Set<string>();
  for (const f of files) {
    const content = readFileSync(join(schemaDir, f), "utf8");
    // Match pgTable("name", ...) — \s* in JS regex matches newlines too,
    // so this works for both single-line and multi-line pgTable() calls.
    const re = /pgTable\s*\(\s*["']([^"']+)["']/g;
    let m: RegExpExecArray | null;
    while ((m = re.exec(content)) !== null) {
      tables.add(m[1]);
    }
  }
  return tables;
}

export function extractCopyTableNames(filePath: string): Set<string> {
  const content = readFileSync(filePath, "utf8");
  const tables = new Set<string>();
  // Match the `table: "name"` pattern used inside copyTable() option objects
  const re = /\btable:\s*["']([^"']+)["']/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(content)) !== null) {
    tables.add(m[1]);
  }
  return tables;
}

export function runCoverageCheck(opts: {
  schemaTables: Set<string>;
  backupTables: Set<string>;
  restoreTables: Set<string>;
  intentionalSkips: Record<string, string>;
  restoreSkipExtra: Record<string, string>;
}): { failed: boolean; warnings: string[]; errors: string[] } {
  const {
    schemaTables,
    backupTables,
    restoreTables,
    intentionalSkips,
    restoreSkipExtra,
  } = opts;

  let failed = false;
  const warnings: string[] = [];
  const errors: string[] = [];

  // Check 1: every schema table must be covered by backup+restore or skip list
  for (const table of [...schemaTables].sort()) {
    const inBackup = backupTables.has(table);
    const inRestore = restoreTables.has(table);
    const skipReason = intentionalSkips[table];

    if (inBackup && inRestore) continue; // ✓ fully covered

    if (skipReason) {
      // Reject TODO entries — they must be resolved by adding real coverage
      if (skipReason.startsWith("TODO:")) {
        errors.push(
          `  ✗  ${table}\n     INTENTIONAL_SKIPS entry begins with "TODO:" — either add copyTable() calls to both scripts, or replace the TODO with a genuine reason for skipping.`,
        );
        failed = true;
      }
      continue; // intentionally skipped (non-TODO)
    }

    // If in backup but not restore, check RESTORE_SKIP_EXTRA first
    if (inBackup && !inRestore && restoreSkipExtra[table]) {
      // Handled in Check 2 below — don't double-report
      continue;
    }

    // Not covered and not in any skip list → fail
    const where: string[] = [];
    if (!inBackup) where.push("backup-to-replit.ts");
    if (!inRestore) where.push("restore-from-replit.ts");
    errors.push(
      `  ✗  ${table}\n     Missing from: ${where.join(", ")}\n     Add copyTable() calls to both scripts, or add to INTENTIONAL_SKIPS with a genuine (non-TODO) reason.`,
    );
    failed = true;
  }

  // Check 2: backup-only tables (in backup but not restore)
  for (const table of [...backupTables].sort()) {
    if (restoreTables.has(table)) continue;
    if (restoreSkipExtra[table]) {
      warnings.push(
        `  ⚠  ${table} (backup only)\n     ${restoreSkipExtra[table]}`,
      );
      continue;
    }
    // Not in skip list — if it's a schema table, Check 1 already flagged it;
    // if it's a backup-internal table (like backup_history), just warn.
    if (!schemaTables.has(table)) {
      warnings.push(
        `  ⚠  ${table}\n     In backup-to-replit.ts but not in schema or restore — may be a backup-internal table. Verify intentionality.`,
      );
    }
  }

  return { failed, warnings, errors };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const schemaTables = extractSchemaTables(
  join(REPO_ROOT, "lib", "db", "src", "schema"),
);
const backupTables = extractCopyTableNames(
  join(REPO_ROOT, "scripts", "src", "backup-to-replit.ts"),
);
const restoreTables = extractCopyTableNames(
  join(REPO_ROOT, "scripts", "src", "restore-from-replit.ts"),
);

const { failed, warnings, errors } = runCoverageCheck({
  schemaTables,
  backupTables,
  restoreTables,
  intentionalSkips: INTENTIONAL_SKIPS,
  restoreSkipExtra: RESTORE_SKIP_EXTRA,
});

for (const e of errors) console.error(e);

if (warnings.length > 0) {
  console.log("\nBackup-coverage warnings (non-fatal):");
  for (const w of warnings) console.log(w);
}

if (failed) {
  console.error(
    "\n✗ check-backup-coverage: schema tables are missing from backup/restore scripts.",
  );
  console.error(
    "  For each table above: add copyTable() calls to backup-to-replit.ts AND",
  );
  console.error(
    "  restore-from-replit.ts, or add an entry to INTENTIONAL_SKIPS in",
  );
  console.error(
    "  scripts/src/check-backup-coverage.ts with a genuine (non-TODO) reason.\n",
  );
  process.exit(1);
} else {
  console.log(
    `✓ check-backup-coverage: all ${schemaTables.size} schema tables accounted for.`,
  );
}
