/**
 * Subprocess tests for scaffold-collection-module.ts, run against a temp
 * copy of the real shared files (so anchors are the genuine ones), never
 * against the repo itself.
 *
 * Covers the undo-safety contract:
 *  1. scaffold + undo restores every shared file byte-for-byte and removes
 *     every generated path;
 *  2. undo REFUSES to delete an existing module that was not generated by
 *     the scaffolder (no provenance markers) and leaves it untouched;
 *  3. undo of a never-scaffolded name fails loudly instead of silently
 *     "succeeding".
 */
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { SCAFFOLD_ANCHORS } from "./scaffold-collection-module.js";

const REPO_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../..",
);
const SCRIPT = path.join(
  REPO_ROOT,
  "scripts/src/scaffold-collection-module.ts",
);

const SHARED_FILES = [
  "lib/api-spec/build-spec.ts",
  "lib/db/src/schema/index.ts",
  "lib/db/src/schema-statements.ts",
  "artifacts/api-server/src/routes/index.ts",
  "artifacts/modules/src/App.tsx",
  "artifacts/web/src/config/apps.tsx",
  "lib/elaine-ui/src/AppSwitcher.tsx",
];

function makeTempRoot(): string {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "scaffold-test-"));
  for (const rel of SHARED_FILES) {
    const dest = path.join(root, rel);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(path.join(REPO_ROOT, rel), dest);
  }
  fs.mkdirSync(path.join(root, "lib/api-spec/sources"), { recursive: true });
  return root;
}

function runScaffold(
  root: string,
  args: string[],
): { status: number; output: string } {
  try {
    const out = execFileSync("pnpm", ["exec", "tsx", SCRIPT, ...args], {
      cwd: path.join(REPO_ROOT, "scripts"),
      env: { ...process.env, SCAFFOLD_COLLECTION_ROOT: root },
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
    return { status: 0, output: out };
  } catch (err) {
    const e = err as { status?: number; stdout?: string; stderr?: string };
    return {
      status: e.status ?? 1,
      output: `${e.stdout ?? ""}${e.stderr ?? ""}`,
    };
  }
}

const SPEC = {
  singular: "gizmo",
  plural: "gizmos",
  title: "Gizmos",
  fields: [
    { name: "maker", type: "string", label: "Maker" },
    { name: "year", type: "number", label: "Year" },
  ],
  categories: true,
  photos: true,
  aiAnalysis: false,
  valueTracking: false,
};

// --- 1. scaffold + undo restores shared files byte-for-byte -----------------
{
  const root = makeTempRoot();
  const specPath = path.join(root, "spec.json");
  fs.writeFileSync(specPath, JSON.stringify(SPEC));
  const before = new Map(
    SHARED_FILES.map((rel) => [
      rel,
      fs.readFileSync(path.join(root, rel), "utf8"),
    ]),
  );

  const scaffoldRes = runScaffold(root, [
    "--spec",
    specPath,
    "--no-codegen",
    "--no-format",
  ]);
  assert.equal(
    scaffoldRes.status,
    0,
    `scaffold failed:\n${scaffoldRes.output}`,
  );
  const genFile = path.join(root, "lib/api-spec/sources/gizmos.yaml");
  assert.ok(fs.existsSync(genFile), "generated yaml missing");
  assert.ok(
    fs.readFileSync(genFile, "utf8").includes("scaffold:generated:gizmos"),
    "generated file missing provenance marker",
  );
  assert.ok(
    fs
      .readFileSync(path.join(root, "artifacts/modules/src/App.tsx"), "utf8")
      .includes("scaffold:begin:gizmos"),
    "shared file missing scaffold block",
  );

  // Ownership scoping: every generated item query/mutation must carry the
  // authenticated-user predicate, and category ops must be owner-scoped.
  const itemsRoute = fs.readFileSync(
    path.join(root, "artifacts/api-server/src/routes/gizmos/gizmos.ts"),
    "utf8",
  );
  const ownerPredicates = itemsRoute.match(/eq\(items\.userId, userId\)/g);
  assert.ok(
    ownerPredicates && ownerPredicates.length >= 5,
    `generated items route must scope list/get/patch(x2)/delete to the owner (found ${ownerPredicates?.length ?? 0} predicates)`,
  );
  assert.match(
    itemsRoute,
    /eq\(cats\.userId, userId\)/,
    "category assignment must verify category ownership",
  );
  // Category ownership must be validated BEFORE any item write, so a
  // rejected request persists nothing (no orphan insert, no partial patch).
  const postBody = itemsRoute.slice(
    itemsRoute.indexOf('router.post("/items"'),
    itemsRoute.indexOf('router.get("/items/:id"'),
  );
  assert.ok(
    postBody.indexOf("categoriesOwned(") !== -1 &&
      postBody.indexOf("categoriesOwned(") < postBody.indexOf(".insert(items)"),
    "POST /items must validate category ownership before inserting the item",
  );
  const patchBody = itemsRoute.slice(
    itemsRoute.indexOf('router.patch("/items/:id"'),
    itemsRoute.indexOf('router.delete("/items/:id"'),
  );
  assert.ok(
    patchBody.indexOf("categoriesOwned(") !== -1 &&
      patchBody.indexOf("categoriesOwned(") <
        patchBody.indexOf(".update(items)"),
    "PATCH /items/:id must validate category ownership before updating fields",
  );
  const catsRoute = fs.readFileSync(
    path.join(root, "artifacts/api-server/src/routes/gizmos/categories.ts"),
    "utf8",
  );
  assert.match(
    catsRoute,
    /createCategoryCountOps\(cats, joinTable, joinTable\.\w+,[\s\S]*userColumn: cats\.userId/,
    "generated category count ops must be owner-scoped",
  );
  assert.match(
    catsRoute,
    /eq\(cats\.userId, userId\)/,
    "generated category mutations must be owner-scoped",
  );
  // Two different users must be able to use the same category name:
  // uniqueness is per-owner (user_id, name), never a global name unique.
  const schemaFile = fs.readFileSync(
    path.join(root, "lib/db/src/schema/gizmos.ts"),
    "utf8",
  );
  assert.ok(
    !/name: text\("name"\).notNull\(\).unique\(\)/.test(schemaFile),
    "categories.name must not be globally unique",
  );
  assert.match(
    schemaFile,
    /unique\("gizmos_categories_user_id_name_key"\)\.on\(\s*table\.userId,\s*table\.name,?\s*\)/,
    "categories must have a composite (user_id, name) unique constraint",
  );
  const ddlFile = fs.readFileSync(
    path.join(root, "lib/db/src/schema-statements.ts"),
    "utf8",
  );
  assert.match(
    ddlFile,
    /CONSTRAINT gizmos_categories_user_id_name_key UNIQUE \(user_id, name\)/,
    "generated DDL must declare the composite (user_id, name) unique",
  );
  assert.ok(
    !/gizmos_categories \([^)]*name text NOT NULL UNIQUE/s.test(ddlFile),
    "generated DDL must not declare a global name UNIQUE",
  );

  // Storage adapter generated when photos=true.
  const storageFile = fs.readFileSync(
    path.join(root, "artifacts/api-server/src/lib/gizmos/storage.ts"),
    "utf8",
  );
  assert.match(
    storageFile,
    /buildStorageAdapter\("gizmos"/,
    "storage.ts must configure a bucket named after the plural",
  );
  assert.match(
    storageFile,
    /IMAGE_ONLY_POLICY/,
    "storage.ts must use IMAGE_ONLY_POLICY",
  );

  // Images route generated when photos=true.
  const imagesRoute = fs.readFileSync(
    path.join(root, "artifacts/api-server/src/routes/gizmos/images.ts"),
    "utf8",
  );
  assert.match(
    imagesRoute,
    /multer\(/,
    "images.ts must use multer for uploads",
  );
  assert.match(
    imagesRoute,
    /sniffAndValidateMime/,
    "images.ts must validate MIME (dual-layer rule)",
  );
  assert.match(
    imagesRoute,
    /router\.post\("\/items\/:id\/images"/,
    "images.ts must have a POST upload endpoint",
  );
  assert.match(
    imagesRoute,
    /router\.get\("\/items\/:id\/image"/,
    "images.ts must have a GET primary-image endpoint",
  );
  assert.match(
    imagesRoute,
    /router\.delete\("\/items\/:id\/images\/:imageId"/,
    "images.ts must have a DELETE endpoint",
  );
  assert.match(imagesRoute, /stripMetadata/, "images.ts must strip metadata");
  // Authenticated private photos must never be cached by shared proxies/CDNs.
  assert.ok(
    !imagesRoute.includes("Cache-Control", 0) ||
      !imagesRoute.includes("public,"),
    "images.ts must not use public Cache-Control for authenticated private photos",
  );
  assert.match(
    imagesRoute,
    /Cache-Control.*private/,
    "images.ts must use private Cache-Control for authenticated image routes",
  );
  const ownerChecksInImages = imagesRoute.match(/eq\(items\.userId, userId\)/g);
  assert.ok(
    ownerChecksInImages && ownerChecksInImages.length >= 3,
    `images.ts must scope upload/serve/delete to the owner (found ${ownerChecksInImages?.length ?? 0})`,
  );

  // Add page generated.
  const addPage = fs.readFileSync(
    path.join(root, "artifacts/modules/src/gizmos/pages/add.tsx"),
    "utf8",
  );
  assert.match(addPage, /useCreateGizmo/, "add.tsx must use the create hook");
  assert.match(
    addPage,
    /handleSubmit/,
    "add.tsx must have a form submit handler",
  );
  assert.match(
    addPage,
    /href="\/gizmos"/,
    "add.tsx cancel link must go to the collection",
  );
  assert.match(
    addPage,
    /api\/gizmos\/items\//,
    "add.tsx must POST to the image upload endpoint",
  );
  assert.match(
    addPage,
    /useListGizmoCategories/,
    "add.tsx must load categories when categories=true",
  );
  // Upload response must be checked for success, not treated as always-ok.
  assert.match(
    addPage,
    /uploadRes\.ok/,
    "add.tsx must check the fetch response .ok before treating the upload as successful",
  );

  // Collection page has an add link.
  const collectionPage = fs.readFileSync(
    path.join(root, "artifacts/modules/src/gizmos/pages/collection.tsx"),
    "utf8",
  );
  assert.match(
    collectionPage,
    /href="\/gizmos\/add"/,
    "collection.tsx must link to the add page",
  );

  // Route index mounts images router when photos=true.
  const routeIndex = fs.readFileSync(
    path.join(root, "artifacts/api-server/src/routes/gizmos/index.ts"),
    "utf8",
  );
  assert.match(
    routeIndex,
    /import imagesRouter from "\.\/images"/,
    "route index must import the images router when photos=true",
  );
  assert.match(
    routeIndex,
    /router\.use\(imagesRouter\)/,
    "route index must mount the images router when photos=true",
  );

  // App.tsx registers lazy import + route for the add page.
  const appTsx = fs.readFileSync(
    path.join(root, "artifacts/modules/src/App.tsx"),
    "utf8",
  );
  assert.match(
    appTsx,
    /GizmosAdd.*=.*lazy.*gizmos\/pages\/add/,
    "App.tsx must lazily import the add page",
  );
  assert.match(
    appTsx,
    /path="\/gizmos\/add"/,
    "App.tsx must register a route for the add page",
  );

  const undoRes = runScaffold(root, ["--undo", "gizmos", "--no-codegen"]);
  assert.equal(undoRes.status, 0, `undo failed:\n${undoRes.output}`);
  for (const rel of SHARED_FILES) {
    assert.equal(
      fs.readFileSync(path.join(root, rel), "utf8"),
      before.get(rel),
      `${rel} not restored byte-for-byte after undo`,
    );
  }
  for (const p of [
    "lib/api-spec/sources/gizmos.yaml",
    "lib/db/src/schema/gizmos.ts",
    "artifacts/api-server/src/lib/gizmos",
    "artifacts/api-server/src/routes/gizmos",
    "artifacts/modules/src/gizmos",
  ]) {
    assert.ok(!fs.existsSync(path.join(root, p)), `${p} not removed by undo`);
  }
  fs.rmSync(root, { recursive: true, force: true });
}

// --- 2. undo refuses an existing NON-scaffolded module ----------------------
{
  const root = makeTempRoot();
  // Simulate a hand-built module (like pottery): files exist at the exact
  // paths the scaffolder would target, but carry no provenance marker.
  const legacyFiles = [
    "lib/api-spec/sources/legacy.yaml",
    "lib/db/src/schema/legacy.ts",
    "artifacts/api-server/src/routes/legacy/index.ts",
    "artifacts/modules/src/legacy/pages/collection.tsx",
  ];
  for (const rel of legacyFiles) {
    const abs = path.join(root, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, "// hand-written module content\n");
  }

  const res = runScaffold(root, ["--undo", "legacy", "--no-codegen"]);
  assert.notEqual(res.status, 0, "undo of unscaffolded module must fail");
  assert.ok(
    res.output.includes("refusing to undo"),
    `expected refusal message, got:\n${res.output}`,
  );
  for (const rel of legacyFiles) {
    assert.ok(
      fs.existsSync(path.join(root, rel)),
      `${rel} was deleted despite refusal`,
    );
    assert.equal(
      fs.readFileSync(path.join(root, rel), "utf8"),
      "// hand-written module content\n",
      `${rel} was modified despite refusal`,
    );
  }
  fs.rmSync(root, { recursive: true, force: true });
}

// --- 3. undo of a never-scaffolded name fails loudly ------------------------
{
  const root = makeTempRoot();
  const res = runScaffold(root, ["--undo", "neverexisted", "--no-codegen"]);
  assert.notEqual(res.status, 0, "undo of nonexistent module must fail");
  assert.ok(
    res.output.includes("nothing to undo"),
    `expected nothing-to-undo message, got:\n${res.output}`,
  );
  fs.rmSync(root, { recursive: true, force: true });
}

// --- 3b. malformed shared markers: undo refuses and deletes NOTHING ---------
{
  const root = makeTempRoot();
  const specPath = path.join(root, "spec.json");
  fs.writeFileSync(specPath, JSON.stringify(SPEC));
  const scaffoldRes = runScaffold(root, [
    "--spec",
    specPath,
    "--no-codegen",
    "--no-format",
  ]);
  assert.equal(
    scaffoldRes.status,
    0,
    `scaffold failed:\n${scaffoldRes.output}`,
  );

  // Truncate one shared insertion: drop its scaffold:end marker line.
  const appTsx = path.join(root, "artifacts/modules/src/App.tsx");
  const truncated = fs
    .readFileSync(appTsx, "utf8")
    .split("\n")
    .filter((l, i, all) => {
      const firstEnd = all.findIndex((x) => x.includes("scaffold:end:gizmos"));
      return i !== firstEnd;
    })
    .join("\n");
  fs.writeFileSync(appTsx, truncated);

  const snapshot = new Map(
    SHARED_FILES.map((rel) => [
      rel,
      fs.readFileSync(path.join(root, rel), "utf8"),
    ]),
  );
  const genFile = path.join(root, "lib/api-spec/sources/gizmos.yaml");
  assert.ok(fs.existsSync(genFile));

  const undoRes = runScaffold(root, ["--undo", "gizmos", "--no-codegen"]);
  assert.notEqual(
    undoRes.status,
    0,
    "undo should refuse when a shared scaffold block is malformed",
  );
  assert.match(undoRes.output, /malformed scaffold marker blocks/);
  // Nothing was deleted: generated files still exist, shared files untouched.
  assert.ok(
    fs.existsSync(genFile),
    "generated yaml was deleted despite malformed shared markers",
  );
  assert.ok(
    fs.existsSync(path.join(root, "artifacts/modules/src/gizmos")),
    "generated module dir was deleted despite malformed shared markers",
  );
  for (const rel of SHARED_FILES) {
    assert.equal(
      fs.readFileSync(path.join(root, rel), "utf8"),
      snapshot.get(rel),
      `${rel} was modified despite the preflight refusal`,
    );
  }
  fs.rmSync(root, { recursive: true, force: true });
}

// --- 4. full integration: scaffold into the real repo, run codegen, --------
// typecheck the affected packages, then undo and verify the repo is clean.
//
// Gated behind SCAFFOLD_INTEGRATION=1: it mutates the real repo and takes
// several minutes (codegen + full root typecheck, twice). Running it inside
// the default suite is hazardous — a killed/timed-out run leaves a
// half-scaffolded module in the working tree (this happened once and the
// junk got committed), and concurrent validation runs would race each other
// on the same shared files. Run it manually after generator changes:
//   SCAFFOLD_INTEGRATION=1 pnpm exec tsx src/scaffold-collection-module.test.ts
if (process.env.SCAFFOLD_INTEGRATION === "1") {
  const gitStatus = () =>
    execFileSync("git", ["status", "--porcelain"], {
      cwd: REPO_ROOT,
      encoding: "utf8",
    }).trim();
  const statusBefore = gitStatus();
  // Random (not just time-based) suffix + exclusive-create ("wx") so a
  // pre-existing file/symlink at a guessed path can never be followed —
  // this write always creates a brand-new, unpredictable path or fails.
  const specPath = path.join(
    os.tmpdir(),
    `scaffold-int-spec-${crypto.randomUUID()}.json`,
  );
  // Unique per-run name so the fixture can never collide with a committed
  // module (or a leftover from an interrupted earlier run) in the real repo.
  const intPlural = `itest${Date.now().toString(36)}x`;
  const intSpec = {
    ...SPEC,
    singular: intPlural.slice(0, -1),
    plural: intPlural,
    title: "Integration Test",
  };
  fs.writeFileSync(specPath, JSON.stringify(intSpec), { flag: "wx" });
  let scaffolded = false;
  try {
    // Scaffold with codegen so the generated Zod schemas + React Query hooks
    // exist for the typecheck below (this is the real end-to-end contract).
    const scaffoldRes = runScaffold(REPO_ROOT, ["--spec", specPath]);
    assert.equal(
      scaffoldRes.status,
      0,
      `integration scaffold failed:\n${scaffoldRes.output}`,
    );
    scaffolded = true;
    // Root typecheck: builds lib project references first (tsc --build), so
    // the new @workspace/db schema exports resolve — a per-package typecheck
    // would read stale lib dist output and fail spuriously.
    try {
      execFileSync("pnpm", ["run", "typecheck"], {
        cwd: REPO_ROOT,
        encoding: "utf8",
        stdio: ["ignore", "pipe", "pipe"],
      });
    } catch (err) {
      const e = err as { stdout?: string; stderr?: string };
      assert.fail(
        `typecheck failed with scaffolded module:\n${e.stdout ?? ""}${e.stderr ?? ""}`,
      );
    }
  } finally {
    if (scaffolded) {
      const undoRes = runScaffold(REPO_ROOT, ["--undo", intPlural]);
      assert.equal(
        undoRes.status,
        0,
        `integration undo failed — repo may be dirty:\n${undoRes.output}`,
      );
    }
    fs.rmSync(specPath, { force: true });
  }
  assert.equal(
    gitStatus(),
    statusBefore,
    "integration scaffold+undo left the repo dirty (git status changed)",
  );
} else {
  console.log(
    "(integration scenario skipped — set SCAFFOLD_INTEGRATION=1 to run it)",
  );
}

// --- 5. every scaffold anchor exists in its real source file ----------------
// Guards against a refactor or concurrent merge accidentally deleting an
// anchor comment and silently breaking the next scaffolder run.
{
  const missing: string[] = [];
  for (const { file, anchor } of SCAFFOLD_ANCHORS) {
    const abs = path.join(REPO_ROOT, file);
    if (!fs.existsSync(abs)) {
      missing.push(`  ${anchor}  →  ${file}  (FILE NOT FOUND)`);
      continue;
    }
    const content = fs.readFileSync(abs, "utf8");
    if (!content.includes(anchor)) {
      missing.push(`  ${anchor}  →  ${file}`);
    }
  }
  assert.equal(
    missing.length,
    0,
    `scaffold anchors missing from their source files:\n${missing.join("\n")}\n\nEach anchor must be present for the collection-module generator to work. ` +
      `If you renamed or refactored the target file, update SCAFFOLD_ANCHORS in scaffold-collection-module.ts too.`,
  );
}

console.log("scaffold-collection-module tests passed");
