// scaffold:generated:magnets — created by scaffold-collection-module; --undo magnets deletes this file
// Generated by scaffold-collection-module for the "magnets" collection.
// Standalone serializer (photos=true) — does NOT use createCollectionSerializer
// because its buildImgsMap strips extra fields before toItem is called.
// storagePath must survive to toItem so primaryImageId can be computed correctly.
import { and, inArray, isNull } from "drizzle-orm";
import { db } from "@workspace/db";
import { pathCacheBuster } from "../path-cache-buster";
import type { MagnetItemRow } from "@workspace/db";
import {
  magnetsItemCategories as itemCategories,
  magnetsCategories as categories,
  magnetsImages,
} from "@workspace/db";
import {
  groupRowsByItem,
  makeFetchRawCategories,
  type CategoryResult,
  type ImageResult,
} from "../collection-item-serializer";

export type { CategoryResult };

/** Extended image shape that carries storagePath for primaryImageId lookup. */
type ImageWithPath = ImageResult & { storagePath: string };

export interface SerializedItem {
  id: number;
  name: string;
  notes: string | null;
  description: string | null;
  lockedFields: string[];
  categories: CategoryResult[];
  images: ImageResult[];
  imageUrl: string | null;
  /** ID of the images-table row that is the current gallery cover, or null. */
  primaryImageId: number | null;
  createdAt: string;
}

const fetchRawCategories = makeFetchRawCategories(itemCategories, categories);

async function fetchExtendedImages(
  itemIds: number[],
): Promise<Array<ImageWithPath & { itemId: number }>> {
  if (itemIds.length === 0) return [];
  const rows = await db
    .select({
      itemId: magnetsImages.itemId,
      id: magnetsImages.id,
      label: magnetsImages.label,
      position: magnetsImages.position,
      storagePath: magnetsImages.storagePath,
    })
    .from(magnetsImages)
    .where(
      and(
        inArray(magnetsImages.itemId, itemIds),
        isNull(magnetsImages.deletedAt),
      ),
    );
  return rows.map((r) => ({
    itemId: r.itemId,
    id: r.id,
    url: `/api/magnets/items/${r.itemId}/images/${r.id}?v=${pathCacheBuster(r.storagePath)}`,
    label: r.label,
    position: r.position,
    storagePath: r.storagePath,
  }));
}

function buildImagesMap(
  rows: Array<ImageWithPath & { itemId: number }>,
): Map<number, ImageWithPath[]> {
  return groupRowsByItem(
    rows,
    (row) => ({
      id: row.id,
      url: row.url,
      label: row.label,
      position: row.position,
      storagePath: row.storagePath,
    }),
    (a, b) => a.position - b.position || a.id - b.id,
  );
}

function toItem(
  row: MagnetItemRow,
  cats: CategoryResult[],
  imgs: ImageWithPath[],
): SerializedItem {
  const primaryImageId =
    row.imagePath != null
      ? (imgs.find((img) => img.storagePath === row.imagePath)?.id ?? null)
      : null;
  return {
    id: row.id,
    name: row.name,
    notes: row.notes,
    description: row.description,
    lockedFields: row.lockedFields ?? [],
    categories: cats,
    images: imgs,
    imageUrl:
      row.imagePath != null
        ? `/api/magnets/items/${row.id}/image?v=${pathCacheBuster(row.imagePath)}`
        : null,
    primaryImageId,
    createdAt: row.createdAt.toISOString(),
  };
}

export async function serializeItem(
  row: MagnetItemRow,
): Promise<SerializedItem> {
  const [rawCats, rawImgs] = await Promise.all([
    fetchRawCategories([row.id]),
    fetchExtendedImages([row.id]),
  ]);
  const cats =
    groupRowsByItem(rawCats, (category) => ({
      id: category.id,
      name: category.name,
      bgColor: category.bgColor,
      textColor: category.textColor,
    })).get(row.id) ?? [];
  const imgsMap = buildImagesMap(rawImgs);
  return toItem(row, cats, imgsMap.get(row.id) ?? []);
}

export async function serializeItems(
  rows: MagnetItemRow[],
): Promise<SerializedItem[]> {
  if (rows.length === 0) return [];
  const itemIds = rows.map((r) => r.id);
  const [rawCats, rawImgs] = await Promise.all([
    fetchRawCategories(itemIds),
    fetchExtendedImages(itemIds),
  ]);
  const catsMap = groupRowsByItem(rawCats, (category) => ({
    id: category.id,
    name: category.name,
    bgColor: category.bgColor,
    textColor: category.textColor,
  }));
  const imgsMap = buildImagesMap(rawImgs);
  return rows.map((row) =>
    toItem(row, catsMap.get(row.id) ?? [], imgsMap.get(row.id) ?? []),
  );
}
