// scaffold:generated:magnets — created by scaffold-collection-module; --undo magnets deletes this file
// Generated by scaffold-collection-module for the "magnets" collection.
import { buildStorageAdapter, IMAGE_ONLY_POLICY } from "../storage-core";
import { sniffImageType, toAiDataUrl } from "../image";

const adapter = buildStorageAdapter("magnets", IMAGE_ONLY_POLICY);

export const uploadImage = adapter.uploadImage;
export const downloadImageBuffer = adapter.downloadImageBuffer;
export const deleteImage = adapter.deleteImage;
export const invalidateImageCache = adapter.invalidateImageCache;

/**
 * Download a stored magnet image and return a data URL bounded to the AI
 * dimension cap (via toAiDataUrl). Suitable for passing directly to vision
 * model calls.
 */
export async function downloadImageAsDataUrl(path: string): Promise<string> {
  const { buffer } = await adapter.downloadImageBuffer(path);
  const contentType = sniffImageType(buffer);
  if (!contentType) {
    throw new Error(`Stored object is not a supported image: ${path}`);
  }
  return toAiDataUrl(buffer, contentType);
}
