/**
 * Gmail label management for the Travels app's "confirmed travel" workflow.
 *
 * Two labels are used, per user's own mailbox:
 *   "Travel"        — applied only when a human confirms an email is travel-
 *                      related (accepting an AI suggestion generated by a
 *                      scan). Never applied automatically just because the AI
 *                      classified a message as travel-related — see
 *                      gmail.ts's link handler. Users may also apply this
 *                      label themselves in Gmail ahead of time; gmail-scan.ts
 *                      treats "Travel"-labeled messages as scan candidates
 *                      too, alongside the keyword pre-filter.
 *   "Batchelor App" — applied alongside "Travel" once that email has actually
 *                      been ingested (linked to a trip as a document), so the
 *                      household can see at a glance in Gmail itself which
 *                      travel emails the app has already reviewed.
 *
 * Requires the gmail.labels scope (see gmail-oauth.ts) — deliberately not the
 * broader gmail.modify, since this app never needs to touch message content,
 * trash, or deletion, only labels.
 */
import { eq } from "drizzle-orm";
import { db, travelsGmailConnections } from "@workspace/db";
import { logger } from "./logger";

const GMAIL_API_BASE = "https://gmail.googleapis.com/gmail/v1";

export const TRAVEL_LABEL_NAME = "Travel";
export const REVIEWED_LABEL_NAME = "Batchelor App";

interface GmailLabel {
  id: string;
  name: string;
}

async function listLabels(accessToken: string): Promise<GmailLabel[]> {
  const res = await fetch(`${GMAIL_API_BASE}/users/me/labels`, {
    headers: { Authorization: `Bearer ${accessToken}` },
  });
  if (!res.ok) {
    throw new Error(`Gmail labels.list failed (${res.status})`);
  }
  const body = (await res.json()) as { labels?: GmailLabel[] };
  return body.labels ?? [];
}

async function createLabel(
  accessToken: string,
  name: string,
): Promise<GmailLabel> {
  const res = await fetch(`${GMAIL_API_BASE}/users/me/labels`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      name,
      labelListVisibility: "labelShow",
      messageListVisibility: "show",
    }),
  });
  if (res.status === 409) {
    // Race: label already exists (e.g. created concurrently, or our cached
    // list was stale) — look it up instead of failing.
    const existing = (await listLabels(accessToken)).find(
      (l) => l.name === name,
    );
    if (existing) return existing;
  }
  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(
      `Gmail labels.create failed (${res.status}): ${body.slice(0, 300)}`,
    );
  }
  return (await res.json()) as GmailLabel;
}

async function getOrCreateLabel(
  accessToken: string,
  name: string,
): Promise<string> {
  const existing = (await listLabels(accessToken)).find((l) => l.name === name);
  if (existing) return existing.id;
  const created = await createLabel(accessToken, name);
  return created.id;
}

/**
 * Resolve this user's "Travel" and "Batchelor App" label ids, creating
 * either label in their Gmail account the first time it's needed, and
 * caching the ids on their connection row (label ids are per-account and
 * stable for the label's lifetime, so this avoids a labels.list round trip
 * on every message link).
 */
export async function getOrCreateUserLabels(
  userId: number,
  accessToken: string,
): Promise<{ travelLabelId: string; reviewedLabelId: string }> {
  const [connection] = await db
    .select({
      travelLabelId: travelsGmailConnections.travelLabelId,
      reviewedLabelId: travelsGmailConnections.reviewedLabelId,
    })
    .from(travelsGmailConnections)
    .where(eq(travelsGmailConnections.userId, userId))
    .limit(1);

  const travelLabelId =
    connection?.travelLabelId ??
    (await getOrCreateLabel(accessToken, TRAVEL_LABEL_NAME));
  const reviewedLabelId =
    connection?.reviewedLabelId ??
    (await getOrCreateLabel(accessToken, REVIEWED_LABEL_NAME));

  if (
    travelLabelId !== connection?.travelLabelId ||
    reviewedLabelId !== connection?.reviewedLabelId
  ) {
    await db
      .update(travelsGmailConnections)
      .set({ travelLabelId, reviewedLabelId, updatedAt: new Date() })
      .where(eq(travelsGmailConnections.userId, userId));
  }

  return { travelLabelId, reviewedLabelId };
}

export async function applyLabelsToMessage(
  accessToken: string,
  messageId: string,
  labelIds: string[],
): Promise<void> {
  const res = await fetch(
    `${GMAIL_API_BASE}/users/me/messages/${messageId}/modify`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ addLabelIds: labelIds }),
    },
  );
  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(
      `Gmail messages.modify failed (${res.status}): ${body.slice(0, 300)}`,
    );
  }
}

/**
 * Best-effort: resolve this user's labels and apply "Travel" + "Batchelor
 * App" to a message. Failures are logged and swallowed by the caller — a
 * Gmail-side label write should never block trip-document ingestion, which
 * has already succeeded by the time this is called.
 */
export async function markMessageAsIngestedTravel(
  userId: number,
  accessToken: string,
  messageId: string,
): Promise<void> {
  try {
    const { travelLabelId, reviewedLabelId } = await getOrCreateUserLabels(
      userId,
      accessToken,
    );
    await applyLabelsToMessage(accessToken, messageId, [
      travelLabelId,
      reviewedLabelId,
    ]);
  } catch (err) {
    logger.warn(
      { err, userId, messageId },
      "gmail-labels: failed to apply Travel/Batchelor App labels",
    );
  }
}
