// Generated by scripts/src/elaine-app-operation-catalog.ts.
// Do not edit by hand. The checked-in OpenAPI specification and reviewed
// website operation inventory are authoritative.
export const ELAINE_APP_OPERATION_CATALOG = [
  {
    operationId: "addFabricIdentifier",
    method: "POST",
    path: "/quilting/fabrics/{id}/identifiers",
    domain: "quilting",
    summary: "Add an identifier to a fabric",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["identifierType", "value"],
        properties: {
          identifierType: {
            type: "string",
            enum: ["sku", "selvedge", "barcode", "other"],
          },
          value: {
            type: "string",
            minLength: 1,
          },
          source: {
            type: "string",
            nullable: true,
          },
          notes: {
            type: "string",
            nullable: true,
          },
        },
      },
    },
  },
  {
    operationId: "addReaction",
    method: "POST",
    path: "/messenger/messages/{id}/reactions",
    domain: "messenger",
    summary: "Add an emoji reaction to a message (idempotent)",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["emoji"],
        properties: {
          emoji: {
            type: "string",
          },
        },
      },
    },
  },
  {
    operationId: "applyFabricIdentityResearch",
    method: "PATCH",
    path: "/quilting/fabrics/{id}/identity-research/{researchId}",
    domain: "quilting",
    summary: "Apply a research candidate to the fabric",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "researchId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["candidateIndex"],
        properties: {
          candidateIndex: {
            type: "integer",
            minimum: 0,
          },
          fields: {
            type: "array",
            items: {
              type: "string",
            },
            description:
              "Specific fields to apply (defaults to all non-locked fields)",
          },
        },
      },
    },
  },
  {
    operationId: "applyPatternAnalysis",
    method: "POST",
    path: "/quilting/patterns/{id}/analyses/{analysisId}/apply",
    domain: "quilting",
    summary:
      "Push shopping-needed items from an analysis into the shopping list",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "analysisId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: false,
      schema: {
        type: "object",
        properties: {
          requirementIds: {
            type: "array",
            items: {
              type: "integer",
            },
            nullable: true,
          },
        },
      },
    },
  },
  {
    operationId: "assignUnmatchedDocument",
    method: "PATCH",
    path: "/travels/documents/{docId}/assign",
    domain: "travels",
    summary: "Assign an unmatched document to a trip",
    access: "action",
    parameters: [
      {
        name: "docId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["tripId"],
        properties: {
          tripId: {
            type: "integer",
          },
        },
      },
    },
  },
  {
    operationId: "bulkCreatePackingItems",
    method: "POST",
    path: "/travels/trips/{id}/packing/items/bulk",
    domain: "travels",
    summary: "Add multiple items to a trip's packing list",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["items"],
        properties: {
          items: {
            type: "array",
            items: {
              type: "object",
              required: ["text"],
              properties: {
                text: {
                  type: "string",
                },
              },
            },
          },
        },
      },
    },
  },
  {
    operationId: "bulkReanalyzePatterns",
    method: "POST",
    path: "/quilting/patterns/bulk-reanalyze",
    domain: "patterns",
    summary: "Re-run AI analysis on multiple patterns",
    access: "action",
    parameters: [],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["ids"],
        properties: {
          ids: {
            type: "array",
            items: {
              type: "integer",
            },
            maxItems: 50,
          },
        },
      },
    },
  },
  {
    operationId: "bulkReanalyzeQuilts",
    method: "POST",
    path: "/quilting/quilts/bulk-reanalyze",
    domain: "quilts",
    summary: "Re-run AI analysis on multiple quilts",
    access: "action",
    parameters: [],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["ids"],
        properties: {
          ids: {
            type: "array",
            items: {
              type: "integer",
            },
            maxItems: 50,
          },
        },
      },
    },
  },
  {
    operationId: "cancelJob",
    method: "POST",
    path: "/jobs/{id}/cancel",
    domain: "jobs",
    summary: "Cancel a nonterminal job (owner only)",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "clearConversation",
    method: "DELETE",
    path: "/messenger/conversations/{id}/messages",
    domain: "messenger",
    summary: "Clear all messages (soft-delete only, keeps conversation)",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "compareFabric",
    method: "POST",
    path: "/quilting/compare",
    domain: "compare",
    summary: "Check if a fabric photo matches anything in the collection",
    access: "action",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "comparePottery",
    method: "POST",
    path: "/pottery/compare",
    domain: "compare",
    summary: "Compare a candidate photo against the collection",
    access: "action",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "createBlockTemplate",
    method: "POST",
    path: "/quilting/block-templates",
    domain: "Block Templates",
    summary: "Save a new block design as a reusable template",
    access: "action",
    parameters: [],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["name", "gridW", "gridH", "cells"],
        properties: {
          name: {
            type: "string",
            minLength: 1,
            maxLength: 120,
          },
          tags: {
            type: "array",
            items: {
              type: "string",
            },
          },
          gridW: {
            type: "integer",
            minimum: 1,
            maximum: 20,
          },
          gridH: {
            type: "integer",
            minimum: 1,
            maximum: 20,
          },
          cells: {
            type: "array",
            items: {
              type: "string",
            },
          },
          seams: {
            type: "array",
            items: {
              type: "object",
              required: ["axis", "pos", "cellIdx"],
              properties: {
                axis: {
                  type: "string",
                  enum: ["h", "v"],
                },
                pos: {
                  type: "integer",
                },
                cellIdx: {
                  type: "integer",
                },
                clipStart: {
                  type: "number",
                  nullable: true,
                },
                clipEnd: {
                  type: "number",
                  nullable: true,
                },
              },
            },
          },
          blockSizeInches: {
            type: "number",
            nullable: true,
            minimum: 1,
            maximum: 120,
          },
          seamAllowanceInches: {
            type: "number",
            nullable: true,
            minimum: 0.0625,
            maximum: 1,
          },
        },
      },
    },
  },
  {
    operationId: "createConversation",
    method: "POST",
    path: "/messenger/conversations",
    domain: "messenger",
    summary: "Create a new conversation (DM or group)",
    access: "action",
    parameters: [],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["participantIds"],
        properties: {
          name: {
            type: "string",
            nullable: true,
          },
          isDirect: {
            type: "boolean",
          },
          participantIds: {
            type: "array",
            items: {
              type: "integer",
            },
          },
        },
      },
    },
  },
  {
    operationId: "createPackingTemplate",
    method: "POST",
    path: "/travels/packing-templates",
    domain: "travels",
    summary: "Save a new packing template",
    access: "action",
    parameters: [],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["name", "items"],
        properties: {
          name: {
            type: "string",
          },
          items: {
            type: "array",
            items: {
              type: "string",
            },
          },
        },
      },
    },
  },
  {
    operationId: "createPatternVariant",
    method: "POST",
    path: "/quilting/patterns/{id}/variants",
    domain: "quilting",
    summary: "Create a new variant for a pattern",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["name"],
        properties: {
          name: {
            type: "string",
            minLength: 1,
            maxLength: 120,
          },
          finishedWidth: {
            type: "number",
            nullable: true,
          },
          finishedHeight: {
            type: "number",
            nullable: true,
          },
          sizeUnit: {
            type: "string",
            nullable: true,
          },
          blockCount: {
            type: "integer",
            nullable: true,
          },
          colorwayDescription: {
            type: "string",
            nullable: true,
          },
          notes: {
            type: "string",
            nullable: true,
          },
        },
      },
    },
  },
  {
    operationId: "createWatchlistItem",
    method: "POST",
    path: "/pottery/watchlist",
    domain: "pottery",
    summary: "Create a new watchlist item",
    access: "action",
    parameters: [],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["title", "keywords"],
        properties: {
          title: {
            type: "string",
            minLength: 1,
            maxLength: 200,
          },
          keywords: {
            type: "string",
            minLength: 1,
            maxLength: 500,
          },
          priceMinUsd: {
            type: ["number", "null"],
          },
          priceMaxUsd: {
            type: ["number", "null"],
          },
        },
      },
    },
  },
  {
    operationId: "deleteBlockTemplate",
    method: "DELETE",
    path: "/quilting/block-templates/{id}",
    domain: "Block Templates",
    summary: "Delete a block template",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "deleteConversation",
    method: "DELETE",
    path: "/messenger/conversations/{id}",
    domain: "messenger",
    summary: "Permanently delete a conversation and all its messages",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "deleteFabricIdentifier",
    method: "DELETE",
    path: "/quilting/fabrics/{id}/identifiers/{identifierId}",
    domain: "quilting",
    summary: "Delete a fabric identifier",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "identifierId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "deleteFabricImage",
    method: "DELETE",
    path: "/quilting/fabrics/{id}/images/{imageId}",
    domain: "fabrics",
    summary: "Delete a supplemental fabric image",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "imageId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "deleteMessage",
    method: "DELETE",
    path: "/messenger/messages/{id}",
    domain: "messenger",
    summary: "Soft-delete a message",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "deleteOrnamentUnusedCategories",
    method: "DELETE",
    path: "/ornaments/categories/unused",
    domain: "ornaments",
    summary: "Delete all categories that have no ornaments assigned",
    access: "action",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "deletePackingTemplate",
    method: "DELETE",
    path: "/travels/packing-templates/{templateId}",
    domain: "travels",
    summary: "Delete a packing template",
    access: "action",
    parameters: [
      {
        name: "templateId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "deletePatternImage",
    method: "DELETE",
    path: "/quilting/patterns/{id}/images/{imageId}",
    domain: "patterns",
    summary: "Delete a supplemental pattern image",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "imageId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "deletePatternVariant",
    method: "DELETE",
    path: "/quilting/patterns/{id}/variants/{variantId}",
    domain: "quilting",
    summary: "Delete a variant",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "variantId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "deletePotteryUnusedCategories",
    method: "DELETE",
    path: "/pottery/categories/unused",
    domain: "pottery",
    summary: "Delete all categories that have no pieces assigned",
    access: "action",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "deleteQuiltImage",
    method: "DELETE",
    path: "/quilting/quilts/{id}/images/{imageId}",
    domain: "quilts",
    summary: "Delete a supplemental quilt image",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "imageId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "deleteQuiltingUnusedCategories",
    method: "DELETE",
    path: "/quilting/categories/unused",
    domain: "categories",
    summary: "Delete all categories with no assignments",
    access: "action",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "deleteTripDocument",
    method: "DELETE",
    path: "/travels/trips/{id}/documents/{docId}",
    domain: "travels",
    summary: "Delete a trip document",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "docId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "deleteUnmatchedDocument",
    method: "DELETE",
    path: "/travels/documents/{docId}",
    domain: "travels",
    summary: "Discard an unmatched document",
    access: "action",
    parameters: [
      {
        name: "docId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "deleteWatchlistItem",
    method: "DELETE",
    path: "/pottery/watchlist/{id}",
    domain: "pottery",
    summary: "Delete a watchlist item",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "detectBlockSeams",
    method: "POST",
    path: "/quilting/blocks/detect-seams",
    domain: "blocks",
    summary: "Use AI to detect seam positions from a block photo",
    access: "action",
    parameters: [],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["image", "gridW", "gridH"],
        properties: {
          image: {
            type: "string",
            description:
              "Base64 data URL of the block photo (JPEG or PNG, max ~1.5 MB)",
          },
          gridW: {
            type: "integer",
            minimum: 1,
            maximum: 20,
          },
          gridH: {
            type: "integer",
            minimum: 1,
            maximum: 20,
          },
        },
      },
    },
  },
  {
    operationId: "dismissWatchlistAlert",
    method: "PATCH",
    path: "/pottery/watchlist/{id}/alerts/{alertId}/dismiss",
    domain: "pottery",
    summary: "Dismiss a watchlist alert",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "alertId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "editMessage",
    method: "PATCH",
    path: "/messenger/messages/{id}",
    domain: "messenger",
    summary: "Edit the body of your own last message",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["body"],
        properties: {
          body: {
            type: "string",
          },
        },
      },
    },
  },
  {
    operationId: "enrichPattern",
    method: "POST",
    path: "/quilting/patterns/{id}/enrich",
    domain: "patterns",
    summary: "Enrich designer metadata via AI web search (Perplexity)",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "estimatePotteryMarketValue",
    method: "POST",
    path: "/pottery/items/{id}/estimate-market-value",
    domain: "pottery",
    summary: "Look up eBay sold-listing prices and cache them on the item",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: false,
      schema: {
        type: "object",
        properties: {
          force: {
            type: "boolean",
            description:
              "When true, skip the 7-day staleness cache and fire a fresh Apify sold-listings run regardless of the last fetch date.\n",
          },
        },
      },
    },
  },
  {
    operationId: "exportOperationEvents",
    method: "GET",
    path: "/operations/export",
    domain: "operations",
    summary: "Export sanitized external operation events as CSV (owner only)",
    access: "read",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "extractPatternBlocks",
    method: "POST",
    path: "/quilting/patterns/{id}/extract-blocks",
    domain: "patterns",
    summary: "Extract block grid schema from pattern image via AI",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "extractPatternRequirements",
    method: "POST",
    path: "/quilting/patterns/{id}/variants/{variantId}/extract-requirements",
    domain: "quilting",
    summary: "Use AI to extract fabric requirements from pattern image/notes",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "variantId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "getBlock",
    method: "GET",
    path: "/quilting/blocks/{id}",
    domain: "blocks",
    summary: "Get a block design by ID",
    access: "read",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "getBlockTemplate",
    method: "GET",
    path: "/quilting/block-templates/{id}",
    domain: "Block Templates",
    summary: "Get a single block template by ID",
    access: "read",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "getCollectionStats",
    method: "GET",
    path: "/pottery/stats",
    domain: "stats",
    summary: "Collection statistics",
    access: "read",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "getConversationMessages",
    method: "GET",
    path: "/messenger/conversations/{id}/messages",
    domain: "messenger",
    summary: "Get messages for a conversation",
    access: "read",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "since",
        in: "query",
        required: false,
        schema: {
          type: "string",
        },
      },
      {
        name: "before",
        in: "query",
        required: false,
        schema: {
          type: "string",
        },
      },
      {
        name: "limit",
        in: "query",
        required: false,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "getFabricPairings",
    method: "GET",
    path: "/quilting/fabrics/{id}/pairings",
    domain: "fabrics",
    summary:
      "Get up to 4 stash fabrics that pair well with this one (embedding similarity)",
    access: "read",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "getJob",
    method: "GET",
    path: "/jobs/{id}",
    domain: "jobs",
    summary: "Get one durable job with attempts (owner only)",
    access: "read",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "getJobsHealth",
    method: "GET",
    path: "/jobs/health",
    domain: "jobs",
    summary: "Get durable queue health (owner only)",
    access: "read",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "getLayout",
    method: "GET",
    path: "/quilting/layouts/{id}",
    domain: "layouts",
    summary: "Get a quilt layout by ID",
    access: "read",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "getLinkPreview",
    method: "GET",
    path: "/messenger/link-preview",
    domain: "messenger",
    summary: "Get cached OG link preview for a URL",
    access: "read",
    parameters: [
      {
        name: "url",
        in: "query",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "getOperationsSummary",
    method: "GET",
    path: "/operations/summary",
    domain: "operations",
    summary: "Summarize provider spend, latency, and reliability (owner only)",
    access: "read",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "getPattern",
    method: "GET",
    path: "/quilting/patterns/{id}",
    domain: "patterns",
    summary: "Get a quilt pattern by ID",
    access: "read",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "getPreferences",
    method: "GET",
    path: "/hub/preferences",
    domain: "hub",
    summary: "Get the current user's hub dashboard widget layout",
    access: "read",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "getQuilt",
    method: "GET",
    path: "/quilting/quilts/{id}",
    domain: "quilts",
    summary: "Get a finished quilt by ID",
    access: "read",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "getShoppingItem",
    method: "GET",
    path: "/quilting/shopping/{id}",
    domain: "shopping",
    summary: "Get a shopping item by ID",
    access: "read",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "getShoppingStats",
    method: "GET",
    path: "/quilting/shopping/stats",
    domain: "shopping",
    summary: "Budget summary statistics",
    access: "read",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "getStaleCount",
    method: "GET",
    path: "/quilting/stats/stale",
    domain: "stats",
    summary: "Count fabrics and patterns missing an AI embedding",
    access: "read",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "getStats",
    method: "GET",
    path: "/quilting/stats",
    domain: "stats",
    summary: "Get collection statistics",
    access: "read",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "getUnreadCount",
    method: "GET",
    path: "/messenger/conversations/unread-count",
    domain: "messenger",
    summary:
      "Total unread message count across all participant conversations (for badge)",
    access: "read",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "getUsedFabricIds",
    method: "GET",
    path: "/quilting/fabrics/used-ids",
    domain: "fabrics",
    summary: "Get IDs of fabrics linked to at least one finished quilt",
    access: "read",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "getWeatherConfig",
    method: "GET",
    path: "/hub/weather-config",
    domain: "hub",
    summary: "Get the current user's saved weather widget location/unit",
    access: "read",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "importPatternFromUrl",
    method: "POST",
    path: "/quilting/patterns/import-url",
    domain: "patterns",
    summary: "Import pattern info from a URL using AI",
    access: "action",
    parameters: [],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["url"],
        properties: {
          url: {
            type: "string",
            format: "uri",
          },
        },
      },
    },
  },
  {
    operationId: "labBulkCreaseFix",
    method: "POST",
    path: "/quilting/lab/bulk-crease-fix",
    domain: "lab",
    summary:
      "Auto-remove creases from the default image of multiple fabrics and set the result as the new default (owner only)",
    access: "action",
    parameters: [],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["ids"],
        properties: {
          ids: {
            type: "array",
            items: {
              type: "integer",
            },
            minItems: 1,
            maxItems: 10,
            description:
              "Fabric IDs to process in this batch (max 10 per request)",
          },
        },
      },
    },
  },
  {
    operationId: "labDetectCreases",
    method: "POST",
    path: "/quilting/lab/detect-creases",
    domain: "lab",
    summary: "Detect fabric creases via AI vision (owner only)",
    access: "action",
    parameters: [],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          fabricId: {
            type: "integer",
            description:
              "ID of the fabric to analyse (mutually exclusive with sourceDataUrl)",
          },
          sourceDataUrl: {
            type: "string",
            description:
              "Base64 data URL of a fresh test photo (mutually exclusive with fabricId)",
          },
        },
      },
    },
  },
  {
    operationId: "labRemoveCreasesOpenai",
    method: "POST",
    path: "/quilting/lab/remove-creases/openai",
    domain: "lab",
    summary: "Inpaint crease areas with OpenAI gpt-image-2 (owner only)",
    access: "action",
    parameters: [],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          fabricId: {
            type: "integer",
          },
          sourceDataUrl: {
            type: "string",
          },
          maskDataUrl: {
            type: "string",
            description:
              "Mask PNG as data URL. When omitted, a full-coverage white mask is used — the AI scans the entire image and removes any creases it finds.",
          },
          prompt: {
            type: "string",
            description:
              "Optional inpainting prompt; defaults to the server-side crease-removal prompt.",
          },
        },
      },
    },
  },
  {
    operationId: "listBlocks",
    method: "GET",
    path: "/quilting/blocks",
    domain: "blocks",
    summary: "List all saved block designs",
    access: "read",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "listBlockTemplates",
    method: "GET",
    path: "/quilting/block-templates",
    domain: "Block Templates",
    summary: "List all saved block templates (household-shared)",
    access: "read",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "listConversations",
    method: "GET",
    path: "/messenger/conversations",
    domain: "messenger",
    summary: "List conversations the current user participates in",
    access: "read",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "listHouseholdMembers",
    method: "GET",
    path: "/messenger/conversations/members",
    domain: "messenger",
    summary: "List all household member accounts",
    access: "read",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "listJobs",
    method: "GET",
    path: "/jobs",
    domain: "jobs",
    summary: "List durable jobs (owner only)",
    access: "read",
    parameters: [
      {
        name: "type",
        in: "query",
        required: false,
        schema: {
          type: "string",
        },
      },
      {
        name: "status",
        in: "query",
        required: false,
        schema: {
          type: "string",
        },
      },
      {
        name: "parentJobId",
        in: "query",
        required: false,
        schema: {
          type: "integer",
        },
      },
      {
        name: "limit",
        in: "query",
        required: false,
        schema: {
          type: "integer",
          maximum: 250,
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "listLayouts",
    method: "GET",
    path: "/quilting/layouts",
    domain: "layouts",
    summary: "List all saved quilt layouts",
    access: "read",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "listOperationBudgets",
    method: "GET",
    path: "/operations/budgets",
    domain: "operations",
    summary: "List provider budget policies (owner only)",
    access: "read",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "listOperationEvents",
    method: "GET",
    path: "/operations/events",
    domain: "operations",
    summary: "List sanitized external operation events (owner only)",
    access: "read",
    parameters: [
      {
        name: "provider",
        in: "query",
        required: false,
        schema: {
          type: "string",
        },
      },
      {
        name: "limit",
        in: "query",
        required: false,
        schema: {
          type: "integer",
          maximum: 250,
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "listOperationProviders",
    method: "GET",
    path: "/operations/providers",
    domain: "operations",
    summary: "List observed providers (owner only)",
    access: "read",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "loadPackingTemplate",
    method: "POST",
    path: "/travels/trips/{id}/packing/load-template/{templateId}",
    domain: "travels",
    summary: "Merge a template's items into the trip's packing list",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "templateId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "lookupOrnamentBookValue",
    method: "POST",
    path: "/ornaments/items/{id}/book-value-lookup",
    domain: "ornaments",
    summary:
      "Look up and save the current book/insurance value from hallmarkornaments.com or hookedonhallmark.com",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "markMessageRead",
    method: "POST",
    path: "/messenger/messages/{id}/read",
    domain: "messenger",
    summary: "Mark a message (and all prior in conversation) as read",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "overrideOperationBudget",
    method: "POST",
    path: "/operations/budgets/{id}/override",
    domain: "operations",
    summary: "Temporarily override a budget policy (owner only)",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["expiresAt"],
        properties: {
          expiresAt: {
            type: "string",
            format: "date-time",
          },
        },
      },
    },
  },
  {
    operationId: "paletteMatchFabrics",
    method: "POST",
    path: "/quilting/tools/palette-match",
    domain: "tools",
    summary:
      "Extract a colour palette from an inspiration image and find matching fabrics",
    access: "action",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "paletteMatchPatterns",
    method: "POST",
    path: "/quilting/tools/palette-match-patterns",
    domain: "tools",
    summary:
      "Extract a colour palette from an inspiration image and find matching quilt patterns",
    access: "action",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "paletteMatchQuilts",
    method: "POST",
    path: "/quilting/tools/palette-match-quilts",
    domain: "tools",
    summary:
      "Extract a colour palette from an inspiration image and find matching finished quilts",
    access: "action",
    parameters: [],
    requestBody: null,
  },
  {
    operationId: "patchBlockTemplate",
    method: "PATCH",
    path: "/quilting/block-templates/{id}",
    domain: "Block Templates",
    summary: "Rename or retag a block template",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          name: {
            type: "string",
            minLength: 1,
            maxLength: 120,
          },
          tags: {
            type: "array",
            items: {
              type: "string",
            },
          },
          gridW: {
            type: "integer",
            minimum: 1,
            maximum: 20,
          },
          gridH: {
            type: "integer",
            minimum: 1,
            maximum: 20,
          },
          cells: {
            type: "array",
            items: {
              type: "string",
            },
          },
          seams: {
            type: "array",
            items: {
              type: "object",
              required: ["axis", "pos", "cellIdx"],
              properties: {
                axis: {
                  type: "string",
                  enum: ["h", "v"],
                },
                pos: {
                  type: "integer",
                },
                cellIdx: {
                  type: "integer",
                },
                clipStart: {
                  type: "number",
                  nullable: true,
                },
                clipEnd: {
                  type: "number",
                  nullable: true,
                },
              },
            },
          },
          blockSizeInches: {
            type: "number",
            nullable: true,
            minimum: 1,
            maximum: 120,
          },
          seamAllowanceInches: {
            type: "number",
            nullable: true,
            minimum: 0.0625,
            maximum: 1,
          },
        },
      },
    },
  },
  {
    operationId: "reanalyzeFabric",
    method: "POST",
    path: "/quilting/fabrics/{id}/reanalyze",
    domain: "fabrics",
    summary: "Re-run AI analysis on a fabric using its existing photos",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "reanalyzeOrnament",
    method: "POST",
    path: "/ornaments/items/{id}/reanalyze",
    domain: "ornaments",
    summary: "Re-run AI analysis on an ornament",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "reanalyzePattern",
    method: "POST",
    path: "/quilting/patterns/{id}/reanalyze",
    domain: "patterns",
    summary: "Re-run AI analysis on a pattern using its existing photo",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "reanalyzePottery",
    method: "POST",
    path: "/pottery/items/{id}/reanalyze",
    domain: "pottery",
    summary: "Re-run AI analysis on a pottery piece",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "reanalyzeQuilt",
    method: "POST",
    path: "/quilting/quilts/{id}/reanalyze",
    domain: "quilts",
    summary: "Re-run AI analysis on a quilt using its existing photo",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "refreshAllOrnamentData",
    method: "POST",
    path: "/ornaments/items/{id}/refresh-all",
    domain: "ornaments",
    summary:
      "Refresh all AI and market data — reanalyze images, book value, eBay price, and AI appraisal all at once",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "removeReaction",
    method: "DELETE",
    path: "/messenger/messages/{id}/reactions/{emoji}",
    domain: "messenger",
    summary: "Remove your emoji reaction from a message",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "emoji",
        in: "path",
        required: true,
        schema: {
          type: "string",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "renameOrnamentCategory",
    method: "PATCH",
    path: "/ornaments/categories/{id}",
    domain: "ornaments",
    summary: "Rename a category",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["name"],
        properties: {
          name: {
            type: "string",
            minLength: 1,
            maxLength: 50,
          },
          bgColor: {
            type: ["string", "null"],
          },
          textColor: {
            type: ["string", "null"],
          },
        },
      },
    },
  },
  {
    operationId: "renamePotteryCategory",
    method: "PATCH",
    path: "/pottery/categories/{id}",
    domain: "pottery",
    summary: "Rename a category",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["name"],
        properties: {
          name: {
            type: "string",
            minLength: 1,
            maxLength: 50,
          },
          bgColor: {
            type: "string",
            nullable: true,
          },
          textColor: {
            type: "string",
            nullable: true,
          },
        },
      },
    },
  },
  {
    operationId: "reorderPackingItems",
    method: "POST",
    path: "/travels/trips/{id}/packing/items/reorder",
    domain: "travels",
    summary:
      "Batch-update sort order for packing items (drag-and-drop reorder)",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["order"],
        properties: {
          order: {
            type: "array",
            items: {
              type: "integer",
            },
          },
        },
      },
    },
  },
  {
    operationId: "retryJob",
    method: "POST",
    path: "/jobs/{id}/retry",
    domain: "jobs",
    summary: "Retry a failed or dead-letter job (owner only)",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "runFabricIdentityResearch",
    method: "POST",
    path: "/quilting/fabrics/{id}/identity-research",
    domain: "quilting",
    summary: "Run an AI identity-research job for a fabric",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "runOrnamentAiAppraisal",
    method: "POST",
    path: "/ornaments/items/{id}/ai-appraisal",
    domain: "ornaments",
    summary: "Run AI collector appraisal on an ornament and save the result",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "runPatternAnalysis",
    method: "POST",
    path: "/quilting/patterns/{id}/analyses",
    domain: "quilting",
    summary: "Run a can-i-make-this analysis against the fabric stash",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: false,
      schema: {
        type: "object",
        properties: {
          variantId: {
            type: "integer",
            nullable: true,
          },
          assumptions: {
            type: "object",
            nullable: true,
          },
        },
      },
    },
  },
  {
    operationId: "savePatternRequirements",
    method: "PUT",
    path: "/quilting/patterns/{id}/variants/{variantId}/requirements",
    domain: "quilting",
    summary: "Replace all fabric requirements for a variant",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "variantId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["requirements"],
        properties: {
          requirements: {
            type: "array",
            items: {
              type: "object",
              required: ["role"],
              properties: {
                role: {
                  type: "string",
                },
                colorDescription: {
                  type: "string",
                  nullable: true,
                },
                quantityYards: {
                  type: "number",
                  nullable: true,
                },
                quantityFatQuarters: {
                  type: "number",
                  nullable: true,
                },
                widthAssumptionInches: {
                  type: "number",
                  nullable: true,
                },
                suggestedSearchQuery: {
                  type: "string",
                  nullable: true,
                },
              },
            },
          },
        },
      },
    },
  },
  {
    operationId: "scanWatchlistItem",
    method: "POST",
    path: "/pottery/watchlist/{id}/scan",
    domain: "pottery",
    summary: "Run an on-demand eBay scan and upsert new alerts",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "sendMessage",
    method: "POST",
    path: "/messenger/conversations/{id}/messages",
    domain: "messenger",
    summary: "Send a message in a conversation",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["body"],
        properties: {
          body: {
            type: "string",
          },
          attachments: {
            type: "array",
            items: {
              type: "object",
              required: ["storagePath", "mimeType", "fileName", "sizeBytes"],
              properties: {
                storagePath: {
                  type: "string",
                },
                mimeType: {
                  type: "string",
                },
                fileName: {
                  type: "string",
                },
                sizeBytes: {
                  type: "integer",
                },
              },
            },
          },
        },
      },
    },
  },
  {
    operationId: "setFabricImageDefault",
    method: "POST",
    path: "/quilting/fabrics/{id}/images/{imageId}/set-default",
    domain: "fabrics",
    summary: "Set a supplemental image as the fabric's default photo",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "imageId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "setPatternImageDefault",
    method: "POST",
    path: "/quilting/patterns/{id}/images/{imageId}/set-default",
    domain: "patterns",
    summary: "Set a supplemental image as the pattern's default photo",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "imageId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: false,
      schema: {
        type: "object",
        properties: {
          expectedVersion: {
            type: "string",
            maxLength: 64,
            description:
              "The v cache-buster from the supplemental image URL being promoted. When provided, the server verifies the image's storage path still hashes to this value before swapping (compare-and-swap); a mismatch returns 409 so a retry cannot reverse an applied swap.",
          },
        },
      },
    },
  },
  {
    operationId: "setQuiltImageDefault",
    method: "POST",
    path: "/quilting/quilts/{id}/images/{imageId}/set-default",
    domain: "quilts",
    summary: "Set a supplemental image as the quilt's default photo",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "imageId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: false,
      schema: {
        type: "object",
        properties: {
          expectedVersion: {
            type: "string",
            maxLength: 64,
            description:
              "The v cache-buster from the supplemental image URL being promoted. When provided, the server verifies the image's storage path still hashes to this value before swapping (compare-and-swap); a mismatch returns 409 so a retry cannot reverse an applied swap.",
          },
        },
      },
    },
  },
  {
    operationId: "suggestShoppingItemPrice",
    method: "POST",
    path: "/quilting/shopping/{id}/suggest-price",
    domain: "shopping",
    summary: "Look up Etsy listings and suggest a price for this shopping item",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: false,
      schema: {
        type: "object",
        properties: {
          itemType: {
            type: "string",
            enum: ["pattern", "fabric", "other"],
            default: "other",
          },
          designer: {
            type: ["string", "null"],
          },
          manufacturer: {
            type: ["string", "null"],
          },
          colorway: {
            type: ["string", "null"],
          },
        },
      },
    },
  },
  {
    operationId: "travelsCheckReservationNow",
    method: "POST",
    path: "/travels/reservations/{id}/check-now",
    domain: "travels",
    summary: "Manually trigger a monitoring check for a reservation",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "travelsCreateReservation",
    method: "POST",
    path: "/travels/trips/{tripId}/reservations",
    domain: "travels",
    summary: "Create a reservation linked to a trip",
    access: "action",
    parameters: [
      {
        name: "tripId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          documentId: {
            type: "integer",
          },
          reservationType: {
            type: "string",
            enum: ["flight", "hotel", "rental_car", "rail", "general"],
          },
          providerName: {
            type: "string",
          },
          confirmationRef: {
            type: "string",
          },
          passengerNames: {
            type: "array",
            items: {
              type: "string",
            },
          },
          segments: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: true,
            },
          },
          checkInDate: {
            type: "string",
            format: "date",
          },
          checkOutDate: {
            type: "string",
            format: "date",
          },
          destinationIata: {
            type: "string",
          },
          originIata: {
            type: "string",
          },
          rawExtracted: {
            type: "object",
            additionalProperties: true,
          },
          monitoringEnabled: {
            type: "boolean",
          },
          monitoringPolicy: {
            type: "string",
            enum: ["minimal", "standard", "aggressive", "paused"],
          },
        },
      },
    },
  },
  {
    operationId: "travelsDecideChangeEvent",
    method: "POST",
    path: "/travels/changes/{id}/decision",
    domain: "travels",
    summary: "Accept, reject, or otherwise decide on a change event",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["action"],
        properties: {
          action: {
            type: "string",
            enum: [
              "accept",
              "reject",
              "keep_current",
              "mark_source_incorrect",
              "disable_monitoring",
            ],
          },
          notes: {
            type: "string",
          },
        },
      },
    },
  },
  {
    operationId: "travelsDeleteReservation",
    method: "DELETE",
    path: "/travels/reservations/{id}",
    domain: "travels",
    summary: "Delete a reservation",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: null,
  },
  {
    operationId: "travelsUpdateMonitoringPreferences",
    method: "PUT",
    path: "/travels/monitoring/preferences",
    domain: "travels",
    summary: "Update monitoring preferences for the current user",
    access: "action",
    parameters: [],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          monitoringEnabled: {
            type: "boolean",
          },
          weatherAlerts: {
            type: "boolean",
          },
          checkInReminders: {
            type: "boolean",
          },
          documentReminders: {
            type: "boolean",
          },
          minSeverity: {
            type: "string",
            enum: ["informational", "attention", "important", "critical"],
          },
          notifyChannels: {
            type: "object",
            properties: {
              inApp: {
                type: "boolean",
              },
              email: {
                type: "boolean",
              },
            },
          },
          scheduleChangeThresholdMinutes: {
            type: "integer",
          },
        },
      },
    },
  },
  {
    operationId: "travelsUpdateReservation",
    method: "PATCH",
    path: "/travels/reservations/{id}",
    domain: "travels",
    summary: "Update a reservation",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          documentId: {
            type: "integer",
          },
          reservationType: {
            type: "string",
            enum: ["flight", "hotel", "rental_car", "rail", "general"],
          },
          providerName: {
            type: "string",
          },
          confirmationRef: {
            type: "string",
          },
          passengerNames: {
            type: "array",
            items: {
              type: "string",
            },
          },
          segments: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: true,
            },
          },
          checkInDate: {
            type: "string",
            format: "date",
          },
          checkOutDate: {
            type: "string",
            format: "date",
          },
          destinationIata: {
            type: "string",
          },
          originIata: {
            type: "string",
          },
          rawExtracted: {
            type: "object",
            additionalProperties: true,
          },
          monitoringEnabled: {
            type: "boolean",
          },
          monitoringPolicy: {
            type: "string",
            enum: ["minimal", "standard", "aggressive", "paused"],
          },
        },
      },
    },
  },
  {
    operationId: "travelsUpdateReservationMonitoring",
    method: "POST",
    path: "/travels/reservations/{id}/monitoring",
    domain: "travels",
    summary: "Enable, disable, or configure monitoring for a reservation",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          monitoringEnabled: {
            type: "boolean",
          },
          monitoringPolicy: {
            type: "string",
            enum: ["minimal", "standard", "aggressive", "paused"],
          },
        },
      },
    },
  },
  {
    operationId: "updateBlock",
    method: "PATCH",
    path: "/quilting/blocks/{id}",
    domain: "blocks",
    summary: "Update a block design",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          name: {
            type: "string",
            minLength: 1,
            maxLength: 100,
          },
          gridSize: {
            type: "integer",
            enum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
          },
          cells: {
            type: "array",
            items: {
              type: "string",
            },
          },
          seams: {
            type: "array",
            items: {
              type: "object",
              required: ["axis", "pos", "cellIdx"],
              properties: {
                axis: {
                  type: "string",
                  enum: ["h", "v"],
                },
                pos: {
                  type: "integer",
                  description: "Perpendicular position in half-cell units",
                },
                cellIdx: {
                  type: "integer",
                  description: "Row index (h seams) or column index (v seams)",
                },
                clipStart: {
                  type: "number",
                  description: "Fractional clip start (0–1) within the cell",
                },
                clipEnd: {
                  type: "number",
                  description: "Fractional clip end (0–1) within the cell",
                },
              },
            },
            description: "H/V seam lines to persist with the block",
          },
          blockSizeInches: {
            type: "number",
            nullable: true,
            minimum: 1,
            maximum: 120,
          },
          categoryNames: {
            type: "array",
            items: {
              type: "string",
            },
            description:
              "Full replacement list of category names (replaces existing assignments)",
          },
          seamAllowanceInches: {
            type: "number",
            nullable: true,
            minimum: 0.0625,
            maximum: 1,
          },
        },
      },
    },
  },
  {
    operationId: "updateConversation",
    method: "PATCH",
    path: "/messenger/conversations/{id}",
    domain: "messenger",
    summary: "Rename or archive/unarchive a conversation",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          name: {
            type: "string",
            nullable: true,
          },
          archived: {
            type: "boolean",
          },
        },
      },
    },
  },
  {
    operationId: "updateFabricImage",
    method: "PATCH",
    path: "/quilting/fabrics/{id}/images/{imageId}",
    domain: "fabrics",
    summary: "Update a supplemental fabric image label/position",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "imageId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          label: {
            type: "string",
            nullable: true,
          },
          position: {
            type: "integer",
          },
        },
      },
    },
  },
  {
    operationId: "updateLayout",
    method: "PATCH",
    path: "/quilting/layouts/{id}",
    domain: "layouts",
    summary: "Update a quilt layout",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          name: {
            type: "string",
            minLength: 1,
            maxLength: 100,
          },
          rows: {
            type: "integer",
            minimum: 1,
            maximum: 16,
          },
          cols: {
            type: "integer",
            minimum: 1,
            maximum: 16,
          },
          cells: {
            type: "array",
            items: {
              type: "object",
              required: ["blockId", "rotation"],
              properties: {
                blockId: {
                  type: "integer",
                  nullable: true,
                },
                rotation: {
                  type: "integer",
                  enum: [0, 90, 180, 270],
                },
              },
            },
          },
          sashingWidthInches: {
            type: "number",
            nullable: true,
            minimum: 0,
            maximum: 6,
          },
          sashingColor: {
            type: "string",
            nullable: true,
          },
          borderWidthInches: {
            type: "number",
            nullable: true,
            minimum: 0,
            maximum: 6,
          },
          borderColor: {
            type: "string",
            nullable: true,
          },
          cornerstoneColor: {
            type: "string",
            nullable: true,
            description:
              "Hex colour for cornerstone squares (null = no cornerstones)",
          },
          categoryNames: {
            type: "array",
            items: {
              type: "string",
              maxLength: 100,
            },
            maxItems: 20,
          },
        },
      },
    },
  },
  {
    operationId: "updateOperationBudget",
    method: "PUT",
    path: "/operations/budgets/{id}",
    domain: "operations",
    summary: "Update a budget policy (owner only)",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: [
          "softThresholdUsd",
          "hardThresholdUsd",
          "enabled",
          "degradationAction",
        ],
        properties: {
          softThresholdUsd: {
            type: "number",
          },
          hardThresholdUsd: {
            type: "number",
          },
          enabled: {
            type: "boolean",
          },
          degradationAction: {
            type: "string",
          },
        },
      },
    },
  },
  {
    operationId: "updateOrnamentCategoryColors",
    method: "PUT",
    path: "/ornaments/categories/{id}/colors",
    domain: "ornaments",
    summary: "Update a category's background and text colours",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          bgColor: {
            type: ["string", "null"],
          },
          textColor: {
            type: ["string", "null"],
          },
        },
      },
    },
  },
  {
    operationId: "updateOrnamentImage",
    method: "PATCH",
    path: "/ornaments/items/{id}/images/{imageId}",
    domain: "ornaments",
    summary: "Update a supplemental image's label or position",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "imageId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          label: {
            type: ["string", "null"],
          },
          position: {
            type: "integer",
          },
        },
      },
    },
  },
  {
    operationId: "updatePackingItem",
    method: "PATCH",
    path: "/travels/trips/{id}/packing/items/{itemId}",
    domain: "travels",
    summary: "Update a packing item (toggle packed, rename, reorder)",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "itemId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          text: {
            type: "string",
          },
          packed: {
            type: "boolean",
          },
          sortOrder: {
            type: "integer",
          },
        },
      },
    },
  },
  {
    operationId: "updatePatternImage",
    method: "PATCH",
    path: "/quilting/patterns/{id}/images/{imageId}",
    domain: "patterns",
    summary: "Update a supplemental pattern image",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "imageId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          label: {
            type: "string",
            nullable: true,
          },
          position: {
            type: "integer",
          },
        },
      },
    },
  },
  {
    operationId: "updatePatternVariant",
    method: "PATCH",
    path: "/quilting/patterns/{id}/variants/{variantId}",
    domain: "quilting",
    summary: "Update a variant",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "variantId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["name"],
        properties: {
          name: {
            type: "string",
            minLength: 1,
            maxLength: 120,
          },
          finishedWidth: {
            type: "number",
            nullable: true,
          },
          finishedHeight: {
            type: "number",
            nullable: true,
          },
          sizeUnit: {
            type: "string",
            nullable: true,
          },
          blockCount: {
            type: "integer",
            nullable: true,
          },
          colorwayDescription: {
            type: "string",
            nullable: true,
          },
          notes: {
            type: "string",
            nullable: true,
          },
        },
      },
    },
  },
  {
    operationId: "updatePotteryCategoryColors",
    method: "PUT",
    path: "/pottery/categories/{id}/colors",
    domain: "pottery",
    summary: "Update a category's background and text colours",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          bgColor: {
            type: "string",
            nullable: true,
          },
          textColor: {
            type: "string",
            nullable: true,
          },
        },
      },
    },
  },
  {
    operationId: "updatePotteryImage",
    method: "PATCH",
    path: "/pottery/items/{id}/images/{imageId}",
    domain: "pottery",
    summary: "Update a supplemental image's label or position",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "imageId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          label: {
            type: ["string", "null"],
          },
          position: {
            type: "integer",
          },
        },
      },
    },
  },
  {
    operationId: "updatePreferences",
    method: "PUT",
    path: "/hub/preferences",
    domain: "hub",
    summary: "Save the current user's hub dashboard widget layout",
    access: "action",
    parameters: [],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["slots"],
        properties: {
          slots: {
            type: "array",
            maxItems: 60,
            items: {
              description:
                'A static catalogue widget slot ({t:"s",id}) or a configurable RSS instance slot ({t:"r",iid,title,url}). Union validated client-side; represented loosely here since Zod uses a discriminated union that Orval renders as a plain object.',
              type: "object",
              required: ["t"],
              properties: {
                t: {
                  type: "string",
                  enum: ["s", "r"],
                },
                id: {
                  type: "string",
                },
                iid: {
                  type: "string",
                },
                title: {
                  type: "string",
                },
                url: {
                  type: "string",
                },
              },
            },
          },
          appCardOrder: {
            type: "array",
            maxItems: 20,
            items: {
              type: "string",
              maxLength: 64,
            },
          },
        },
      },
    },
  },
  {
    operationId: "updateQuilt",
    method: "PATCH",
    path: "/quilting/quilts/{id}",
    domain: "quilts",
    summary: "Update quilt metadata",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          name: {
            type: "string",
          },
          dateCompleted: {
            type: "string",
            nullable: true,
          },
          sizeWidth: {
            type: "number",
            nullable: true,
          },
          sizeHeight: {
            type: "number",
            nullable: true,
          },
          recipient: {
            type: "string",
            nullable: true,
          },
          notes: {
            type: "string",
            nullable: true,
          },
          lockedFields: {
            type: "array",
            items: {
              type: "string",
            },
          },
          categories: {
            type: "array",
            maxItems: 50,
            items: {
              type: "string",
              maxLength: 100,
            },
          },
          linkedFabricIds: {
            type: "array",
            items: {
              type: "integer",
            },
          },
          linkedPatternIds: {
            type: "array",
            items: {
              type: "integer",
            },
          },
          completionPercentage: {
            type: "integer",
            minimum: 0,
            maximum: 100,
            nullable: true,
          },
        },
      },
    },
  },
  {
    operationId: "updateQuiltImage",
    method: "PATCH",
    path: "/quilting/quilts/{id}/images/{imageId}",
    domain: "quilts",
    summary: "Update a supplemental quilt image",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "imageId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          label: {
            type: "string",
            nullable: true,
          },
          position: {
            type: "integer",
          },
        },
      },
    },
  },
  {
    operationId: "updateQuiltingCategoryColors",
    method: "PUT",
    path: "/quilting/categories/{id}/colors",
    domain: "categories",
    summary: "Update category badge colours",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          bgColor: {
            type: "string",
            nullable: true,
          },
          textColor: {
            type: "string",
            nullable: true,
          },
        },
      },
    },
  },
  {
    operationId: "updateTripDocument",
    method: "PATCH",
    path: "/travels/trips/{id}/documents/{docId}",
    domain: "travels",
    summary: "Correct/update the extracted data for a trip document",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
      {
        name: "docId",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          extractedData: {
            type: "object",
            additionalProperties: true,
          },
          lockedFields: {
            type: "array",
            items: {
              type: "string",
            },
          },
          title: {
            type: "string",
            nullable: true,
          },
          documentType: {
            type: "string",
            nullable: true,
          },
          iconOverride: {
            type: "string",
            nullable: true,
          },
        },
      },
    },
  },
  {
    operationId: "updateWatchlistItem",
    method: "PATCH",
    path: "/pottery/watchlist/{id}",
    domain: "pottery",
    summary: "Update a watchlist item",
    access: "action",
    parameters: [
      {
        name: "id",
        in: "path",
        required: true,
        schema: {
          type: "integer",
        },
      },
    ],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        properties: {
          title: {
            type: "string",
          },
          keywords: {
            type: "string",
          },
          priceMinUsd: {
            type: ["number", "null"],
          },
          priceMaxUsd: {
            type: ["number", "null"],
          },
          active: {
            type: "boolean",
          },
        },
      },
    },
  },
  {
    operationId: "updateWeatherConfig",
    method: "PUT",
    path: "/hub/weather-config",
    domain: "hub",
    summary: "Save the current user's weather widget location/unit",
    access: "action",
    parameters: [],
    requestBody: {
      required: true,
      schema: {
        type: "object",
        required: ["city", "country", "lat", "lon", "unit"],
        properties: {
          city: {
            type: "string",
            maxLength: 200,
          },
          country: {
            type: "string",
            maxLength: 100,
          },
          lat: {
            type: "number",
            minimum: -90,
            maximum: 90,
          },
          lon: {
            type: "number",
            minimum: -180,
            maximum: 180,
          },
          unit: {
            type: "string",
            enum: ["celsius", "fahrenheit"],
          },
        },
      },
    },
  },
] as const;
