// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ornament-detail/InlineFields.tsx": () => import("../components/mockups/ornament-detail/InlineFields.tsx"),
  "./components/mockups/ornament-detail/InlineFieldsWithCalc.tsx": () => import("../components/mockups/ornament-detail/InlineFieldsWithCalc.tsx"),
  "./components/mockups/ornament-detail/MagazineSplit.tsx": () => import("../components/mockups/ornament-detail/MagazineSplit.tsx"),
  "./components/mockups/ornament-detail/TabView.tsx": () => import("../components/mockups/ornament-detail/TabView.tsx"),
  "./components/mockups/ornament-detail/WideCanvas.tsx": () => import("../components/mockups/ornament-detail/WideCanvas.tsx"),
};
