// scaffold:generated:magnets — created by scaffold-collection-module; --undo magnets deletes this file
// Generated by scaffold-collection-module for the "magnets" collection.
// Nav entries register into the shared registry — never hardcode nav arrays.
import { LayoutGrid, Camera, Tags } from "lucide-react";
import { registerFeature } from "@/features/registry";

registerFeature({
  id: "magnets-collection",
  nav: {
    group: "collection",
    href: "/magnets",
    label: "Magnets",
    icon: LayoutGrid,
    order: 10,
  },
});

// Camera Bulk Add is a browser-only feature: it requires camera access and
// binary image upload, which restricted/non-web channels (SMS, voice, Slack)
// do not support. It is surfaced here as a nav entry in the page context
// only — Elaine directs users to this page rather than executing it directly.
registerFeature({
  id: "magnets-bulk-add",
  nav: {
    group: "add",
    href: "/magnets/bulk-add",
    label: "Add Magnets",
    icon: Camera,
    order: 10,
  },
});

registerFeature({
  id: "magnets-categories",
  nav: {
    group: "settings",
    href: "/magnets/categories",
    label: "Categories",
    icon: Tags,
    order: 10,
  },
});
