export * from "./generated/api";
export * from "./generated/api.schemas";
export { setBaseUrl, setAuthTokenGetter, customFetch } from "./custom-fetch";
export type { AuthTokenGetter, CustomFetchOptions } from "./custom-fetch";
export * from "./travels";
export * from "./elaine";

// travels.ts is a hand-maintained parallel implementation of the travels API
// hooks (predates/duplicates what orval now generates for travels paths in
// the OpenAPI spec). Where the same name is generated by orval AND hand-written
// in travels.ts, explicitly re-export the travels.ts version so it wins over
// the ambiguous `export *` above — travels.ts is what every consumer in this
// workspace actually imports and depends on today.
export {
  createTrip,
  deleteTrip,
  deleteTripDocument,
  exploreDestination,
  generateItinerary,
  getGetPackingListQueryKey,
  getGetTravelsStatsQueryKey,
  getGetTravelsStatsQueryOptions,
  getGetTripQueryKey,
  getGetTripQueryOptions,
  getListPackingTemplatesQueryKey,
  getListTripsQueryKey,
  getListTripsQueryOptions,
  getListTripsUrl,
  getTravelsStats,
  getTrip,
  listTripDocuments,
  listTrips,
  rescanTripDocument,
  updateTrip,
  updateTripDocument,
  useBulkCreatePackingItems,
  useCreatePackingItem,
  useCreatePackingTemplate,
  useCreateTrip,
  useDeletePackingItem,
  useDeletePackingTemplate,
  useDeleteTrip,
  useDeleteTripDocument,
  useExploreDestination,
  useGenerateItinerary,
  useGetPackingList,
  useGetTravelsStats,
  useGetTrip,
  useListPackingTemplates,
  useListTrips,
  useLoadPackingTemplate,
  useReorderPackingItems,
  useRescanTripDocument,
  useUpdatePackingItem,
  useUpdateTrip,
  useUpdateTripDocument,
} from "./travels";
