export * from "./generated/api";
export * from "./generated/api.schemas";
export { setBaseUrl, setAuthTokenGetter, customFetch } from "./custom-fetch";
export type { AuthTokenGetter, CustomFetchOptions } from "./custom-fetch";
export * from "./travels";
export * from "./elaine";

// travels.ts is a hand-maintained parallel implementation of the travels API
// hooks (predates/duplicates what orval now generates for travels paths in
// the OpenAPI spec). Where the same name is generated by orval AND hand-written
// in travels.ts, explicitly re-export the travels.ts version so it wins over
// the ambiguous `export *` above — travels.ts is what every consumer in this
// workspace actually imports and depends on today. This is a deliberate,
// documented decision (see replit.md's "travels.ts stays authoritative"
// architecture decision) rather than an oversight — the generated hooks for
// these names differ in call shape (positional args vs {data}/{id,data}
// mutation payloads) and body/type names, so a full migration was judged
// higher-risk than keeping this list in sync.
//
// `pnpm --filter @workspace/scripts run check-travels-overlap` (wired into
// root `typecheck`) fails if this list ever drifts out of sync with the
// actual overlap between travels.ts and the generated files — keep it
// complete when either file's exports change.
export {
  createTrip,
  deleteTrip,
  deleteTripDocument,
  exploreDestination,
  generateItinerary,
  getGetPackingListQueryKey,
  getGetTravelsStatsQueryKey,
  getGetTravelsStatsQueryOptions,
  getGetTripQueryKey,
  getGetTripQueryOptions,
  getListPackingTemplatesQueryKey,
  getListTripsQueryKey,
  getListTripsQueryOptions,
  getListTripsUrl,
  getTravelsStats,
  getTrip,
  listTripDocuments,
  listTrips,
  rescanTripDocument,
  updateTrip,
  updateTripDocument,
  useBulkCreatePackingItems,
  useCreatePackingItem,
  useCreatePackingTemplate,
  useCreateTrip,
  useDeletePackingItem,
  useDeletePackingTemplate,
  useDeleteTrip,
  useDeleteTripDocument,
  useExploreDestination,
  useGenerateItinerary,
  useGetPackingList,
  useGetTravelsStats,
  useGetTrip,
  useListPackingTemplates,
  useListTrips,
  useLoadPackingTemplate,
  useReorderPackingItems,
  useRescanTripDocument,
  useUpdatePackingItem,
  useUpdateTrip,
  useUpdateTripDocument,
} from "./travels";
