// Hand-written hooks for the household-shared Hallmark events feature
// (ornaments_hallmark_events). Not generated by orval — see memory note
// on the js-yaml codegen breakage; follows the same customFetch +
// react-query pattern as the generated hooks.
import {
  useMutation,
  useQuery,
  useQueryClient,
  type UseMutationOptions,
  type UseQueryOptions,
} from "@tanstack/react-query";
import { customFetch } from "./custom-fetch";

export interface OrnamentsHallmarkEvent {
  id: number;
  userId: number | null;
  title: string;
  description?: string | null;
  startDate: string;
  endDate: string;
  googleEventId?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface OrnamentsHallmarkEventInput {
  title: string;
  description?: string | null;
  startDate: string;
  endDate: string;
}

const BASE = "/ornaments/hallmark-events";

export function useListOrnamentsHallmarkEvents(
  options?: Partial<UseQueryOptions<OrnamentsHallmarkEvent[]>>,
) {
  return useQuery<OrnamentsHallmarkEvent[]>({
    queryKey: ["ornaments-hallmark-events"],
    queryFn: () => customFetch<OrnamentsHallmarkEvent[]>(BASE),
    ...options,
  });
}

export function useCreateOrnamentsHallmarkEvent(
  options?: Partial<
    UseMutationOptions<OrnamentsHallmarkEvent, unknown, OrnamentsHallmarkEventInput>
  >,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (data: OrnamentsHallmarkEventInput) =>
      customFetch<OrnamentsHallmarkEvent>(BASE, {
        method: "POST",
        body: JSON.stringify(data),
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["ornaments-hallmark-events"] });
    },
    ...options,
  });
}

export function useUpdateOrnamentsHallmarkEvent(
  options?: Partial<
    UseMutationOptions<
      OrnamentsHallmarkEvent,
      unknown,
      { id: number; data: Partial<OrnamentsHallmarkEventInput> }
    >
  >,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ id, data }) =>
      customFetch<OrnamentsHallmarkEvent>(`${BASE}/${id}`, {
        method: "PATCH",
        body: JSON.stringify(data),
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["ornaments-hallmark-events"] });
    },
    ...options,
  });
}

export function useDeleteOrnamentsHallmarkEvent(
  options?: Partial<UseMutationOptions<void, unknown, number>>,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id: number) =>
      customFetch<void>(`${BASE}/${id}`, { method: "DELETE" }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["ornaments-hallmark-events"] });
    },
    ...options,
  });
}
