/**
 * Read/helper tools whose results must be returned to the model before it can
 * write a grounded answer. Keep this list aligned with the hard-tool executor
 * in Elaine's main streaming chat route.
 */
export const MODEL_VISIBLE_HARD_TOOL_NAMES = new Set<string>([
  "search_household_data",
  "show_trip_card",
  "show_pottery_item",
  "show_fabric_swatch",
  "show_ornament_item",
  "web_search",
  "ebay_search",
  "search_hallmark",
  "search_flights",
  "fetch_page",
  "consult_experts",
  "get_weather_forecast",
  "find_nearby_places",
  "get_route_info",
  "get_air_quality",
  "get_pollen_forecast",
  "calculate_yardage",
  "query_household_data",
  "lookup_product_barcode",
  "summarize_inbox",
  "find_emails_about_topic",
  "get_email_detail",
  "list_notes",
  "get_note",
  "list_notifications",
  "get_notification_counts",
  "get_notification_preferences",
  "list_memories",
  "list_elaine_tasks",
  "get_elaine_task",
  "remember_household_fact",
  "search_trip_documents",
  "show_destination_card",
  "get_exchange_rate",
  "suggest_clothing_layers",
]);

export const MODEL_VISIBLE_HARD_TOOL_STATUS_LABELS: Readonly<
  Record<string, string>
> = {
  search_household_data: "searching your collection",
  show_trip_card: "looking up that trip",
  show_pottery_item: "looking up that pottery piece",
  show_fabric_swatch: "looking up that fabric",
  show_ornament_item: "looking up that ornament",
  web_search: "searching the web",
  ebay_search: "checking eBay sold listings",
  search_hallmark: "searching Hallmark.com",
  search_flights: "checking flight prices",
  fetch_page: "reading that page",
  consult_experts: "checking in with a couple of experts",
  get_weather_forecast: "checking the forecast",
  find_nearby_places: "looking up places",
  get_route_info: "checking travel times",
  get_air_quality: "checking air quality",
  get_pollen_forecast: "checking pollen levels",
  calculate_yardage: "calculating yardage",
  query_household_data: "checking household data",
  lookup_product_barcode: "looking up that barcode",
  summarize_inbox: "reading your inbox",
  find_emails_about_topic: "searching your email",
  get_email_detail: "reading that email",
  list_notes: "reading household notes",
  get_note: "reading that note",
  list_notifications: "checking your notifications",
  get_notification_counts: "counting your notifications",
  get_notification_preferences: "checking notification preferences",
  list_memories: "checking Elaine's memory",
  list_elaine_tasks: "checking background tasks",
  get_elaine_task: "checking that background task",
  remember_household_fact: "saving that memory",
  search_trip_documents: "searching trip documents",
  show_destination_card: "preparing that destination",
  get_exchange_rate: "checking exchange rates",
  suggest_clothing_layers: "preparing clothing recommendations",
};

export const SPECIALIZED_CURRENT_TOOL_NAMES = new Set<string>([
  "ebay_search",
  "get_air_quality",
  "get_exchange_rate",
  "get_pollen_forecast",
  "get_weather_forecast",
  "lookup_product_barcode",
  "search_flights",
  "search_hallmark",
]);
