// scaffold:generated:magnets — created by scaffold-collection-module; --undo magnets deletes this file
// Generated by scaffold-collection-module for the "magnets" collection.
// Composed from the shared category-router-factory — do not hand-roll CRUD.
import { eq } from "drizzle-orm";
import {
  db,
  magnetsCategories as cats,
  magnetsItemCategories as joinTable,
} from "@workspace/db";
import {
  ListMagnetCategoriesResponse,
  ListMagnetCategoriesResponseItem,
  CreateMagnetCategoryBody,
  DeleteMagnetCategoryParams,
  RenameMagnetCategoryParams,
  RenameMagnetCategoryBody,
  MergeMagnetCategoryBody,
  UpdateMagnetCategoryColorsBody,
  UpdateMagnetCategoryColorsParams,
} from "@workspace/api-zod";
import {
  buildCategoryRouter,
  normalizeCategoryNameSimple,
  type CategoryOps,
} from "../../lib/category-router-factory";
import { createCategoryCountOps } from "../../lib/collection-category-ops";

/** Household-shared categories; `userId` records attribution on creation. */
function categoryById(id: number) {
  return eq(cats.id, id);
}

const ops: CategoryOps = {
  ...createCategoryCountOps(cats, joinTable, joinTable.itemId),

  async create(userId, name, bgColor, textColor) {
    await db
      .insert(cats)
      .values({ userId, name, bgColor, textColor })
      .onConflictDoNothing();
    const [row] = await db
      .select({ id: cats.id })
      .from(cats)
      .where(eq(cats.name, name));
    return row.id;
  },

  async rename(id, name, userId) {
    const [updated] = await db
      .update(cats)
      .set({ name })
      .where(categoryById(id))
      .returning({ id: cats.id });
    return !!updated;
  },

  async updateColors(id, bgColor, textColor, userId) {
    const [updated] = await db
      .update(cats)
      .set({ bgColor, textColor })
      .where(categoryById(id))
      .returning({ id: cats.id });
    return !!updated;
  },

  async deleteById(id, userId) {
    const [row] = await db
      .delete(cats)
      .where(categoryById(id))
      .returning({ id: cats.id });
    return !!row;
  },

  async categoryExists(id, userId) {
    const [row] = await db
      .select({ id: cats.id })
      .from(cats)
      .where(categoryById(id));
    return !!row;
  },

  async getAssignmentsForCategory(categoryId, userId) {
    // Ownership of categoryId is checked by categoryExists() before merge.
    void userId;
    return db
      .select({ itemId: joinTable.itemId })
      .from(joinTable)
      .where(eq(joinTable.categoryId, categoryId));
  },

  async reattachAssignments(assignments, targetId, userId) {
    // targetId ownership is checked by categoryExists() before merge.
    void userId;
    const rows = assignments as { itemId: number }[];
    if (rows.length === 0) return;
    await db
      .insert(joinTable)
      .values(rows.map((r) => ({ itemId: r.itemId, categoryId: targetId })))
      .onConflictDoNothing();
  },

  async deleteCategoryRow(id, userId) {
    await db.delete(cats).where(categoryById(id));
  },
};

const { router } = buildCategoryRouter({
  ops,
  normalize: normalizeCategoryNameSimple,
  schemas: {
    listResponse: ListMagnetCategoriesResponse,
    listItem: ListMagnetCategoriesResponseItem,
    createBody: CreateMagnetCategoryBody,
    deleteParams: DeleteMagnetCategoryParams,
    renameParams: RenameMagnetCategoryParams,
    renameBody: RenameMagnetCategoryBody,
    mergeBody: MergeMagnetCategoryBody,
    mergeSourceIdField: "intoId",
    updateColorsBody: UpdateMagnetCategoryColorsBody,
    updateColorsParams: UpdateMagnetCategoryColorsParams,
  },
  mergeResponse: "no-content",
});

export default router;
