// scaffold:generated:magnets — created by scaffold-collection-module; --undo magnets deletes this file
// Generated by scaffold-collection-module for the "magnets" collection.
import { Router, type IRouter } from "express";
import multer from "multer";
import { z } from "zod/v4";
import { and, asc, eq, isNull } from "drizzle-orm";
import {
  db,
  magnetsItems as items,
  magnetsImages as images,
} from "@workspace/db";
import { requireAuth } from "../../middleware/auth";
import { DEFAULT_MULTER_FILE_BYTES } from "../../middleware/uploadSizeGuard";
import {
  createImageFileFilter,
  sniffAndValidateMime,
  isImageMimeType,
  stripMetadata,
} from "@workspace/upload-validation";
import {
  uploadImage,
  downloadImageBuffer,
  deleteImage,
  invalidateImageCache,
} from "../../lib/magnets/storage";
import { pathCacheBuster } from "../../lib/path-cache-buster";

const ALLOWED_IMAGE_TYPES = new Set(["image/jpeg", "image/png", "image/webp"]);
const upload = multer({
  storage: multer.memoryStorage(),
  limits: {
    fileSize: DEFAULT_MULTER_FILE_BYTES,
    files: 1,
    fields: 4,
    fieldSize: 8192,
  },
  fileFilter: createImageFileFilter(ALLOWED_IMAGE_TYPES),
});

const router: IRouter = Router();
router.use(requireAuth);

const IdParams = z.object({ id: z.coerce.number().int().positive() });
const ImageParams = z.object({
  id: z.coerce.number().int().positive(),
  imageId: z.coerce.number().int().positive(),
});
const UpdateImageBody = z.object({
  label: z.string().trim().nullable().optional(),
});

// ---------------------------------------------------------------------------
// GET /items/:id/image — serve the primary image (imagePath on the item row)
// ---------------------------------------------------------------------------
router.get("/items/:id/image", async (req, res) => {
  const { id } = IdParams.parse(req.params);
  const [item] = await db.select().from(items).where(eq(items.id, id));
  if (!item || item.deletedAt || !item.imagePath) {
    res.status(404).json({ error: "Not found" });
    return;
  }
  const { buffer, contentType } = await downloadImageBuffer(item.imagePath);
  res.set("Content-Type", contentType);
  res.set("Cache-Control", "private, max-age=31536000, immutable");
  res.send(buffer);
});

// ---------------------------------------------------------------------------
// GET /items/:id/images/:imageId — serve a specific image by id
// ---------------------------------------------------------------------------
router.get("/items/:id/images/:imageId", async (req, res) => {
  const { id, imageId } = ImageParams.parse(req.params);
  const [item] = await db
    .select({ id: items.id, deletedAt: items.deletedAt })
    .from(items)
    .where(eq(items.id, id));
  if (!item || item.deletedAt) {
    res.status(404).json({ error: "Not found" });
    return;
  }
  const [img] = await db
    .select()
    .from(images)
    .where(
      and(
        eq(images.id, imageId),
        eq(images.itemId, id),
        isNull(images.deletedAt),
      ),
    );
  if (!img) {
    res.status(404).json({ error: "Not found" });
    return;
  }
  const { buffer, contentType } = await downloadImageBuffer(img.storagePath);
  res.set("Content-Type", contentType);
  res.set("Cache-Control", "private, max-age=31536000, immutable");
  res.send(buffer);
});

// ---------------------------------------------------------------------------
// POST /items/:id/images — upload a photo
// ---------------------------------------------------------------------------
router.post("/items/:id/images", upload.single("image"), async (req, res) => {
  const { id } = IdParams.parse(req.params);
  const file = req.file;
  if (!file) {
    res.status(400).json({ error: "No image file provided" });
    return;
  }
  let sniffedType: ReturnType<typeof sniffAndValidateMime>;
  try {
    sniffedType = sniffAndValidateMime(file.buffer, file.mimetype);
  } catch {
    res.status(400).json({
      error: "Unsupported image. Please upload a JPEG, PNG, or WEBP photo.",
    });
    return;
  }
  if (!isImageMimeType(sniffedType)) {
    res.status(400).json({
      error: "Unsupported image. Please upload a JPEG, PNG, or WEBP photo.",
    });
    return;
  }
  const contentType = sniffedType;
  const cleanBuffer = await stripMetadata(file.buffer, contentType);

  const [item] = await db.select().from(items).where(eq(items.id, id));
  if (!item || item.deletedAt) {
    res.status(404).json({ error: "Not found" });
    return;
  }

  // Determine position (append after existing non-deleted images).
  const existing = await db
    .select({ id: images.id })
    .from(images)
    .where(and(eq(images.itemId, id), isNull(images.deletedAt)));
  const position = existing.length;

  const storagePath = await uploadImage(cleanBuffer, contentType);
  const label =
    typeof req.body["label"] === "string" ? req.body["label"] : null;

  const [imgRow] = await db
    .insert(images)
    .values({ itemId: id, storagePath, label, position })
    .returning();

  // First image becomes the primary (gallery cover) automatically.
  if (position === 0) {
    await db
      .update(items)
      .set({ imagePath: storagePath })
      .where(eq(items.id, id));
    invalidateImageCache(storagePath);
  }

  res.status(201).json({
    id: imgRow.id,
    url: `/api/magnets/items/${id}/images/${imgRow.id}?v=${pathCacheBuster(storagePath)}`,
    label: imgRow.label,
    position: imgRow.position,
  });
});

// ---------------------------------------------------------------------------
// PATCH /items/:id/images/:imageId — update a supplemental photo's label
// ---------------------------------------------------------------------------
router.patch("/items/:id/images/:imageId", async (req, res) => {
  const { id, imageId } = ImageParams.parse(req.params);
  const body = UpdateImageBody.parse(req.body);
  const [item] = await db
    .select({ id: items.id, deletedAt: items.deletedAt })
    .from(items)
    .where(eq(items.id, id));
  if (!item || item.deletedAt) {
    res.status(404).json({ error: "Not found" });
    return;
  }
  const [img] = await db
    .select()
    .from(images)
    .where(
      and(
        eq(images.id, imageId),
        eq(images.itemId, id),
        isNull(images.deletedAt),
      ),
    );
  if (!img) {
    res.status(404).json({ error: "Not found" });
    return;
  }
  const [updated] =
    body.label === undefined
      ? [img]
      : await db
          .update(images)
          .set({ label: body.label || null })
          .where(eq(images.id, imageId))
          .returning();
  res.json({
    id: updated.id,
    url: `/api/magnets/items/${id}/images/${updated.id}?v=${pathCacheBuster(updated.storagePath)}`,
    label: updated.label,
    position: updated.position,
  });
});

// ---------------------------------------------------------------------------
// DELETE /items/:id/images/:imageId — remove a photo (soft-delete + cleanup)
// ---------------------------------------------------------------------------
router.delete("/items/:id/images/:imageId", async (req, res) => {
  const { id, imageId } = ImageParams.parse(req.params);
  const [item] = await db.select().from(items).where(eq(items.id, id));
  if (!item || item.deletedAt) {
    res.status(404).json({ error: "Not found" });
    return;
  }
  const [img] = await db
    .select()
    .from(images)
    .where(
      and(
        eq(images.id, imageId),
        eq(images.itemId, id),
        isNull(images.deletedAt),
      ),
    );
  if (!img) {
    res.status(404).json({ error: "Not found" });
    return;
  }
  await db
    .update(images)
    .set({ deletedAt: new Date() })
    .where(eq(images.id, imageId));
  invalidateImageCache(img.storagePath);
  await deleteImage(img.storagePath).catch(() => void 0);

  // If this was the primary, promote the next image (by position).
  if (item.imagePath === img.storagePath) {
    const remaining = await db
      .select()
      .from(images)
      .where(and(eq(images.itemId, id), isNull(images.deletedAt)))
      .orderBy(asc(images.position));
    const next = remaining[0] ?? null;
    await db
      .update(items)
      .set({ imagePath: next?.storagePath ?? null })
      .where(eq(items.id, id));
  }
  res.status(204).end();
});

// ---------------------------------------------------------------------------
// POST /items/:id/images/:imageId/primary — promote to gallery cover
// ---------------------------------------------------------------------------
router.post("/items/:id/images/:imageId/primary", async (req, res) => {
  const { id, imageId } = ImageParams.parse(req.params);
  const [item] = await db.select().from(items).where(eq(items.id, id));
  if (!item || item.deletedAt) {
    res.status(404).json({ error: "Not found" });
    return;
  }
  const [img] = await db
    .select()
    .from(images)
    .where(
      and(
        eq(images.id, imageId),
        eq(images.itemId, id),
        isNull(images.deletedAt),
      ),
    );
  if (!img) {
    res.status(404).json({ error: "Not found" });
    return;
  }
  const [updated] = await db
    .update(items)
    .set({ imagePath: img.storagePath })
    .where(eq(items.id, id))
    .returning();
  res.json({ id: updated.id, imagePath: updated.imagePath });
});

export default router;
