// scaffold:generated:magnets — created by scaffold-collection-module; --undo magnets deletes this file
// Generated by scaffold-collection-module for the "magnets" collection.
import { Router, type IRouter } from "express";
import itemsRouter from "./magnets";
import categoriesRouter from "./categories";

import imagesRouter from "./images";

const router: IRouter = Router();

router.use(itemsRouter);
router.use(categoriesRouter);

router.use(imagesRouter);

export default router;
