// scaffold:generated:magnets — created by scaffold-collection-module; --undo magnets deletes this file
// Generated by scaffold-collection-module for the "magnets" collection.
import { Router, type IRouter } from "express";
import { z } from "zod/v4";
import {
  and,
  asc,
  count,
  desc,
  eq,
  inArray,
  isNull,
  or,
  sql,
  type SQL,
} from "drizzle-orm";
import {
  db,
  magnetsItems as items,
  magnetsItemCategories as itemCategories,
  magnetsCategories as cats,
  magnetsImages as images,
} from "@workspace/db";
import {
  ListMagnetsResponse,
  CreateMagnetBody,
  GetMagnetResponse,
  UpdateMagnetBody,
  ReanalyzeMagnetParams,
  ReanalyzeMagnetResponse,
} from "@workspace/api-zod";
import { requireAuth } from "../../middleware/auth";
import { aiLimiter } from "../../middleware/rateLimit";
import { serializeItem, serializeItems } from "../../lib/magnets/serialize";
import { analyzeMagnetImage } from "../../lib/magnets/openai";
import { downloadImageAsDataUrl } from "../../lib/magnets/storage";
import { resolveOrCreateMagnetCategories } from "../../lib/magnets/resolve-categories";
import { logActivity } from "../../lib/soft-delete";
import { createCollectionTextSearch } from "../../lib/collection-text-search";

const router: IRouter = Router();
router.use(requireAuth);

const IdParams = z.object({ id: z.coerce.number().int().positive() });
const ListQuery = z.object({
  q: z.string().optional(),
  categoryId: z.coerce.number().int().positive().optional(),
  categoryIds: z.array(z.coerce.number().int().positive()).default([]),
  uncategorized: z
    .preprocess(
      (value) => (value === "true" ? true : value === "false" ? false : value),
      z.boolean(),
    )
    .default(false),
  sort: z.enum(["newest", "oldest", "name-asc", "name-desc"]).default("newest"),
  page: z.coerce.number().int().positive().default(1),
  pageSize: z.coerce.number().int().positive().max(200).default(60),
});

/**
 * True when every requested category is in the household catalogue. MUST be
 * checked BEFORE any item insert/update so a rejected request leaves no
 * partial write behind.
 */
async function categoriesExist(categoryIds: number[]): Promise<boolean> {
  if (categoryIds.length === 0) return true;
  const existing = await db
    .select({ id: cats.id })
    .from(cats)
    .where(inArray(cats.id, categoryIds));
  return existing.length === new Set(categoryIds).size;
}

/** Replace an item's category assignments (ownership already validated). */
async function replaceCategories(itemId: number, categoryIds: number[]) {
  await db.delete(itemCategories).where(eq(itemCategories.itemId, itemId));
  if (categoryIds.length > 0) {
    await db
      .insert(itemCategories)
      .values(categoryIds.map((categoryId) => ({ itemId, categoryId })))
      .onConflictDoNothing();
  }
}

// Magnets are household-shared: userId is attribution for the creator, not an
// access boundary. Authentication is still required for every route above.
router.get("/items", async (req, res) => {
  // Express parses a repeated query parameter as an array, but a single
  // categoryIds value is a scalar. Normalize it before validating the query.
  const rawQuery = {
    ...req.query,
    ...(req.query.categoryIds !== undefined && {
      categoryIds: Array.isArray(req.query.categoryIds)
        ? req.query.categoryIds
        : [req.query.categoryIds],
    }),
  };
  const query = ListQuery.parse(rawQuery);
  const selectedCategoryIds = Array.from(
    new Set([
      ...(query.categoryId !== undefined ? [query.categoryId] : []),
      ...query.categoryIds,
    ]),
  );

  const conditions: SQL<unknown>[] = [isNull(items.deletedAt)];
  const textSearch = query.q
    ? createCollectionTextSearch(query.q, {
        title: [items.name],
        broad: [items.notes, items.description],
      })
    : null;
  if (textSearch?.where) conditions.push(textSearch.where);
  if (selectedCategoryIds.length > 0 || query.uncategorized) {
    const categoryClauses: SQL<unknown>[] = [];
    if (selectedCategoryIds.length > 0) {
      categoryClauses.push(sql`exists (
        select 1 from magnets_item_categories mic
        where mic.item_id = ${items.id}
          and mic.category_id in (${sql.join(
            selectedCategoryIds.map((id) => sql`${id}`),
            sql`, `,
          )})
      )
      `);
    }
    if (query.uncategorized) {
      categoryClauses.push(sql`not exists (
        select 1 from magnets_item_categories mic
        where mic.item_id = ${items.id}
      )`);
    }
    conditions.push(or(...(categoryClauses as [SQL, ...SQL[]]))!);
  }

  const where = and(...(conditions as [SQL, ...SQL[]]))!;
  const offset = (query.page - 1) * query.pageSize;
  const orderBy =
    query.sort === "oldest"
      ? [asc(items.createdAt), asc(items.id)]
      : query.sort === "name-asc"
        ? [asc(items.name), asc(items.id)]
        : query.sort === "name-desc"
          ? [desc(items.name), desc(items.id)]
          : [desc(items.createdAt), desc(items.id)];

  const [{ value: total }] = await db
    .select({ value: count() })
    .from(items)
    .where(where);
  const pageRows = await db
    .select()
    .from(items)
    .where(where)
    .orderBy(
      ...(textSearch?.relevance ? [textSearch.relevance] : []),
      ...orderBy,
    )
    .limit(query.pageSize)
    .offset(offset);
  const totalCount = Number(total);
  res.json(
    ListMagnetsResponse.parse({
      items: await serializeItems(pageRows),
      total: totalCount,
      page: query.page,
      pageSize: query.pageSize,
      totalPages: totalCount === 0 ? 1 : Math.ceil(totalCount / query.pageSize),
    }),
  );
});

router.post("/items", async (req, res) => {
  const body = CreateMagnetBody.parse(req.body);
  const userId = req.session.userId!;
  // Validate BEFORE the insert so a rejected request writes nothing.
  if (!(await categoriesExist(body.categoryIds ?? []))) {
    res.status(400).json({ error: "Unknown category id" });
    return;
  }
  const [row] = await db
    .insert(items)
    .values({
      userId,
      name: body.name,
      notes: body.notes ?? null,
      description: body.description,
    })
    .returning();
  if (body.categoryIds && body.categoryIds.length > 0) {
    await replaceCategories(row.id, body.categoryIds);
  }
  res.status(201).json(GetMagnetResponse.parse(await serializeItem(row)));
});

router.get("/items/:id", async (req, res) => {
  const { id } = IdParams.parse(req.params);
  const [row] = await db.select().from(items).where(eq(items.id, id));
  if (!row || row.deletedAt) {
    res.status(404).json({ error: "Not found" });
    return;
  }
  res.json(GetMagnetResponse.parse(await serializeItem(row)));
});

router.patch("/items/:id", async (req, res) => {
  const { id } = IdParams.parse(req.params);
  const body = UpdateMagnetBody.parse(req.body);
  const set: Record<string, unknown> = {};
  if (body.name !== undefined) set.name = body.name;
  if (body.notes !== undefined) set.notes = body.notes;
  if (body.description !== undefined) set.description = body.description;
  if (body.lockedFields !== undefined) set.lockedFields = body.lockedFields;
  const [existing] = await db.select().from(items).where(eq(items.id, id));
  if (!existing || existing.deletedAt) {
    res.status(404).json({ error: "Not found" });
    return;
  }
  // Validate BEFORE any update so a rejected request changes nothing.
  if (
    body.categoryIds !== undefined &&
    !(await categoriesExist(body.categoryIds ?? []))
  ) {
    res.status(400).json({ error: "Unknown category id" });
    return;
  }
  let row = existing;
  if (Object.keys(set).length > 0) {
    [row] = await db.update(items).set(set).where(eq(items.id, id)).returning();
  }
  if (body.categoryIds !== undefined) {
    await replaceCategories(id, body.categoryIds ?? []);
  }
  res.json(GetMagnetResponse.parse(await serializeItem(row)));
});

router.delete("/items/:id", async (req, res) => {
  const { id } = IdParams.parse(req.params);
  const now = new Date();
  const [row] = await db
    .update(items)
    .set({ deletedAt: now })
    .where(eq(items.id, id))
    .returning({ id: items.id });
  if (!row) {
    res.status(404).json({ error: "Not found" });
    return;
  }
  await db.update(images).set({ deletedAt: now }).where(eq(images.itemId, id));
  void logActivity({
    actorUserId: req.session.userId!,
    actorChannel: "web",
    actionType: "delete_magnet",
    entityType: "magnet",
    entityId: id,
    reversible: true,
  });
  res.status(204).end();
});

// ---------------------------------------------------------------------------
// Re-analyse a magnet with AI vision
// ---------------------------------------------------------------------------

// Fixed image-byte safeguard for one analysis request, not owner-facing policy.
const MAX_REANALYZE_IMAGES = 5;

router.post("/items/:id/reanalyze", aiLimiter, async (req, res) => {
  const { id } = ReanalyzeMagnetParams.parse(req.params);
  const userId = req.session.userId!;

  // All authenticated household members can refresh every shared item.
  const [row] = await db.select().from(items).where(eq(items.id, id));
  if (!row || row.deletedAt) {
    res.status(404).json({ error: "Not found" });
    return;
  }
  if (!row.imagePath) {
    res
      .status(422)
      .json({ error: "This magnet has no primary image to analyse." });
    return;
  }

  // Collect supplemental image paths (up to the cap).
  const supplementalRows = await db
    .select({ storagePath: images.storagePath, position: images.position })
    .from(images)
    .where(and(eq(images.itemId, id), isNull(images.deletedAt)))
    .orderBy(images.position);

  const allPaths = [
    row.imagePath,
    ...supplementalRows.map((r) => r.storagePath),
  ].slice(0, MAX_REANALYZE_IMAGES);

  const settled = await Promise.allSettled(
    allPaths.map(downloadImageAsDataUrl),
  );
  const dataUrls = settled
    .filter(
      (s): s is PromiseFulfilledResult<string> => s.status === "fulfilled",
    )
    .map((s) => s.value);

  if (dataUrls.length === 0) {
    res
      .status(422)
      .json({ error: "Could not load any image for this magnet." });
    return;
  }

  const lockedFields = (row.lockedFields as string[]) ?? [];
  const analysis = await analyzeMagnetImage(dataUrls, lockedFields);

  // Apply updates, skipping locked fields.
  const updates: Record<string, unknown> = {};
  if (!lockedFields.includes("name")) updates.name = analysis.name;
  if (!lockedFields.includes("description"))
    updates.description = analysis.description;

  if (Object.keys(updates).length > 0) {
    await db.update(items).set(updates).where(eq(items.id, id));
  }

  // Resolve/create categories from AI suggestions, then merge with existing.
  if (analysis.categories.length > 0) {
    const suggestedIds = await resolveOrCreateMagnetCategories(
      analysis.categories,
      userId,
    );

    if (suggestedIds.length > 0) {
      // Fetch existing assignments to avoid duplicates.
      const existing = await db
        .select({ categoryId: itemCategories.categoryId })
        .from(itemCategories)
        .where(eq(itemCategories.itemId, id));
      const existingSet = new Set(existing.map((e) => e.categoryId));
      const newIds = suggestedIds.filter((cid) => !existingSet.has(cid));
      if (newIds.length > 0) {
        await db
          .insert(itemCategories)
          .values(newIds.map((categoryId) => ({ itemId: id, categoryId })))
          .onConflictDoNothing();
      }
    }
  }

  // Re-fetch the updated row so the response reflects all changes.
  const [updated] = await db.select().from(items).where(eq(items.id, id));

  res.json(ReanalyzeMagnetResponse.parse(await serializeItem(updated)));
});

export default router;
