// scaffold:generated:magnets — created by scaffold-collection-module; --undo magnets deletes this file
// Generated by scaffold-collection-module for the "magnets" collection.
// DDL lives in lib/db/src/schema-statements.ts — keep both in sync.
import { sql } from "drizzle-orm";
import {
  index,
  integer,
  pgTable,
  primaryKey,
  serial,
  text,
  timestamp,
  unique,
} from "drizzle-orm/pg-core";

export const magnetsItems = pgTable(
  "magnets_items",
  {
    id: serial("id").primaryKey(),
    userId: integer("user_id").notNull(),
    name: text("name").notNull(),
    notes: text("notes"),
    description: text("description"),
    imagePath: text("image_path"),
    lockedFields: text("locked_fields")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("magnets_items_name_trgm_idx")
      .using("gin", table.name.op("gin_trgm_ops"))
      .where(sql`${table.deletedAt} IS NULL`),
    index("magnets_items_notes_trgm_idx")
      .using("gin", table.notes.op("gin_trgm_ops"))
      .where(sql`${table.deletedAt} IS NULL`),
    index("magnets_items_description_trgm_idx")
      .using("gin", table.description.op("gin_trgm_ops"))
      .where(sql`${table.deletedAt} IS NULL`),
    index("magnets_items_user_id_idx").on(table.userId),
  ],
).enableRLS();

export type MagnetItemRow = typeof magnetsItems.$inferSelect;
export type InsertMagnetItem = typeof magnetsItems.$inferInsert;

export const magnetsCategories = pgTable(
  "magnets_categories",
  {
    id: serial("id").primaryKey(),
    userId: integer("user_id").notNull(),
    name: text("name").notNull(),
    bgColor: text("bg_color"),
    textColor: text("text_color"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("magnets_categories_user_id_idx").on(table.userId),
    // Household-shared: names are unique across the collection.
    unique("magnets_categories_name_key").on(table.name),
  ],
).enableRLS();

export const magnetsItemCategories = pgTable(
  "magnets_item_categories",
  {
    itemId: integer("item_id")
      .notNull()
      .references(() => magnetsItems.id, { onDelete: "cascade" }),
    categoryId: integer("category_id")
      .notNull()
      .references(() => magnetsCategories.id, { onDelete: "cascade" }),
  },
  (table) => [primaryKey({ columns: [table.itemId, table.categoryId] })],
).enableRLS();

export const magnetsImages = pgTable(
  "magnets_images",
  {
    id: serial("id").primaryKey(),
    itemId: integer("item_id")
      .notNull()
      .references(() => magnetsItems.id, { onDelete: "cascade" }),
    storagePath: text("storage_path").notNull(),
    label: text("label"),
    position: integer("position").notNull().default(0),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [index("magnets_images_item_id_idx").on(table.itemId)],
).enableRLS();
