import { pgTable, serial, integer, text, timestamp } from "drizzle-orm/pg-core";

// Messenger: a genuinely new household-shared feature. Follows the same
// household-sharing pattern as every other collection table — `senderId`
// is attribution-only (who sent the message), never used to filter or gate
// reads. Any authenticated household member may read all messages. A null
// senderId means the message was generated by Elaine (synthetic reply).
export const messengerConversations = pgTable("messenger_conversations", {
  id: serial("id").primaryKey(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
}).enableRLS();

export const messengerMessages = pgTable("messenger_messages", {
  id: serial("id").primaryKey(),
  conversationId: integer("conversation_id").notNull(),
  senderId: integer("sender_id"),
  body: text("body").notNull().default(""),
  readAt: timestamp("read_at", { withTimezone: true }),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
  editedAt: timestamp("edited_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
}).enableRLS();

export const messengerAttachments = pgTable("messenger_attachments", {
  id: serial("id").primaryKey(),
  messageId: integer("message_id").notNull(),
  storagePath: text("storage_path").notNull(),
  mimeType: text("mime_type").notNull(),
  fileName: text("file_name").notNull(),
  sizeBytes: integer("size_bytes").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
}).enableRLS();

export const messengerLinkPreviews = pgTable("messenger_link_previews", {
  id: serial("id").primaryKey(),
  url: text("url").notNull(),
  title: text("title"),
  description: text("description"),
  imageUrl: text("image_url"),
  fetchedAt: timestamp("fetched_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
}).enableRLS();

export type MessengerConversationRow =
  typeof messengerConversations.$inferSelect;
export type InsertMessengerConversation =
  typeof messengerConversations.$inferInsert;
export type MessengerMessageRow = typeof messengerMessages.$inferSelect;
export type InsertMessengerMessage = typeof messengerMessages.$inferInsert;
export type MessengerAttachmentRow = typeof messengerAttachments.$inferSelect;
export type InsertMessengerAttachment =
  typeof messengerAttachments.$inferInsert;
export type MessengerLinkPreviewRow = typeof messengerLinkPreviews.$inferSelect;
export type InsertMessengerLinkPreview =
  typeof messengerLinkPreviews.$inferInsert;
